var c;c||(c=typeof Module !== 'undefined' ? Module : {});var n={},q;for(q in c)c.hasOwnProperty(q)&&(n[q]=c[q]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var t=!1,u=!1,v=!1,aa=!1;
if(c.ENVIRONMENT)if("WEB"===c.ENVIRONMENT)t=!0;else if("WORKER"===c.ENVIRONMENT)u=!0;else if("NODE"===c.ENVIRONMENT)v=!0;else if("SHELL"===c.ENVIRONMENT)aa=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else t="object"===typeof window,u="function"===typeof importScripts,v="object"===typeof process&&"function"===typeof require&&!t&&!u,aa=!t&&!v&&!u;
if(v){var ba,ca;c.read=function(a,b){ba||(ba=require("fs"));ca||(ca=require("path"));a=ca.normalize(a);a=ba.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=c);process.on("uncaughtException",function(a){if(!(a instanceof x))throw a;});process.on("unhandledRejection",
function(){process.exit(1)});c.inspect=function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(t||u)c.read=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)},c.setWindowTitle=function(a){document.title=a};else throw Error("not compiled for this environment");
c.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;c.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||c.print;c.print=c.print;c.printErr=c.printErr;for(q in n)n.hasOwnProperty(q)&&(c[q]=n[q]);n=void 0;function da(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ea={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},fa=0;function assert(a,b){a||y("Assertion failed: "+b)}
var ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ia(a,b){for(var d=b;a[d];)++d;if(16<d-b&&a.subarray&&ha)return ha.decode(a.subarray(b,d));for(d="";;){var e=a[b++];if(!e)return d;if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;if(224==(e&240))e=(e&15)<<12|f<<6|h;else{var g=a[b++]&63;if(240==(e&248))e=(e&7)<<18|f<<12|h<<6|g;else{var k=a[b++]&63;if(248==(e&252))e=(e&3)<<24|f<<18|h<<12|g<<6|k;else{var m=a[b++]&63;e=(e&1)<<30|f<<24|h<<18|g<<12|k<<6|m}}}65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function ja(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}var f=b+1;b=ka(f);d=b;e=z;if(0<f){f=d+f-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);55296<=g&&57343>=g&&(g=65536+((g&1023)<<10)|a.charCodeAt(++h)&1023);if(127>=g){if(d>=f)break;e[d++]=g}else{if(2047>=g){if(d+1>=f)break;e[d++]=192|g>>6}else{if(65535>=g){if(d+2>=f)break;e[d++]=224|g>>
12}else{if(2097151>=g){if(d+3>=f)break;e[d++]=240|g>>18}else{if(67108863>=g){if(d+4>=f)break;e[d++]=248|g>>24}else{if(d+5>=f)break;e[d++]=252|g>>30;e[d++]=128|g>>24&63}e[d++]=128|g>>18&63}e[d++]=128|g>>12&63}e[d++]=128|g>>6&63}e[d++]=128|g&63}}e[d]=0}return b}var buffer,z,A,B,la,C,D,ma,na;
function oa(){c.HEAP8=z=new Int8Array(buffer);c.HEAP16=B=new Int16Array(buffer);c.HEAP32=C=new Int32Array(buffer);c.HEAPU8=A=new Uint8Array(buffer);c.HEAPU16=la=new Uint16Array(buffer);c.HEAPU32=D=new Uint32Array(buffer);c.HEAPF32=ma=new Float32Array(buffer);c.HEAPF64=na=new Float64Array(buffer)}var E,F,pa,qa,ra,sa,ta,ua;E=F=qa=ra=sa=ta=ua=0;pa=!1;
function va(){y("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+G+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var xa=c.TOTAL_STACK||5242880,G=c.TOTAL_MEMORY||16777216;G<xa&&c.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+G+"! (TOTAL_STACK="+xa+")");
c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:G/65536,maximum:G/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(G),c.buffer=buffer);oa();C[0]=1668509029;B[1]=25459;if(115!==A[2]||99!==A[3])throw"Runtime error: expected the system to be little-endian!";
function H(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var d=b.m;"number"===typeof d?void 0===b.g?c.dynCall_v(d):c.dynCall_vi(d,b.g):d(void 0===b.g?null:b.g)}}}var ya=[],za=[],Aa=[],Ba=[],Ca=[],Da=!1;function Ea(){var a=c.preRun.shift();ya.unshift(a)}var I=0,Fa=null,J=null;c.preloadedImages={};c.preloadedAudios={};
function Ga(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(w){y(w)}}function b(){return c.wasmBinary||!t&&!u||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function d(a){function d(a){k=a.exports;if(k.memory){a=k.memory;var b=c.buffer;a.byteLength<b.byteLength&&c.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;oa()}c.asm=k;c.usingWasm=!0;I--;c.monitorRunDependencies&&c.monitorRunDependencies(I);0==I&&(null!==Fa&&(clearInterval(Fa),Fa=null),J&&(a=J,J=null,a()))}
function e(a){d(a.instance)}function h(a){b().then(function(a){return WebAssembly.instantiate(a,g)}).then(a).catch(function(a){c.printErr("failed to asynchronously prepare wasm: "+a);y(a)})}if("object"!==typeof WebAssembly)return c.printErr("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return c.printErr("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;g.global={NaN:NaN,Infinity:Infinity};g["global.Math"]=Math;g.env=a;I++;c.monitorRunDependencies&&c.monitorRunDependencies(I);
if(c.instantiateWasm)try{return c.instantiateWasm(g,d)}catch(l){return c.printErr("Module.instantiateWasm callback failed with error: "+l),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ga(f)||"function"!==typeof fetch?h(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),g).then(e).catch(function(a){c.printErr("wasm streaming compile failed: "+a);c.printErr("falling back to ArrayBuffer instantiation");h(e)});return{}}var e="main.wast",f="main.wasm",h=
"main.temp.asm.js";"function"===typeof c.locateFile&&(Ga(e)||(e=c.locateFile(e)),Ga(f)||(f=c.locateFile(f)),Ga(h)||(h=c.locateFile(h)));var g={global:null,env:null,asm2wasm:ea,parent:c},k=null;c.asmPreload=c.asm;var m=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===r)var b=m(a);else a:{var d=c.usingWasm?65536:16777216;0<a%d&&(a+=d-a%d);d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(U){b=null;break a}b=void 0}return b};
var r="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=b.table}b.memoryBase||(b.memoryBase=c.STATIC_BASE);b.tableBase||(b.tableBase=0);b=d(b);assert(b,"no binaryen method succeeded.");return b}})();
var Ha=[function(a,b){c.removeAttribute(a,c.UTF8ToString(b))},function(a,b,d){c.setAttribute(a,c.UTF8ToString(b),c.UTF8ToString(d))},function(a){c.f[a].asmDomRaws=[]},function(a,b){c.f[a].asmDomRaws.push(c.UTF8ToString(b))},function(a,b){a=c.f[a];a.s=b;void 0===a.asmDomEvents&&(a.asmDomEvents={})},function(a,b){b=c.UTF8ToString(b).replace(/^on/,"");a=c.f[a];a.removeEventListener(b,c.h,!1);delete a.asmDomEvents[b]},function(a,b){b=c.UTF8ToString(b).replace(/^on/,"");a=c.f[a];a.addEventListener(b,c.h,
!1);a.asmDomEvents[b]=c.h},function(a,b){return 0===b?c.createElement(c.UTF8ToString(a)):c.createElementNS(c.UTF8ToString(b),c.UTF8ToString(a))},function(a){return c.createTextNode(c.UTF8ToString(a))},function(){return c.createDocumentFragment()},function(a){return c.createComment(c.UTF8ToString(a))},function(a,b){c.appendChild(a,b)},function(a,b,d){c.insertBefore(a,b,d)},function(a){c.removeChild(a)},function(a,b,d){c.insertBefore(a,b,c.nextSibling(d))},function(a,b,d){c.insertBefore(a,b,d)},function(a,
b){c.F(a,c.UTF8ToString(b))},function(a,b){var d=c.parentNode(b);0!==d&&(c.insertBefore(d,a,c.nextSibling(b)),c.removeChild(b))},function(){window.asmDomHelpers.eventProxy=function(a){return c.functionCallback(this.s,a.type,a)};c.G=window.asmDomHelpers.domApi.addNode;c.createElement=window.asmDomHelpers.domApi.createElement;c.createElementNS=window.asmDomHelpers.domApi.createElementNS;c.createTextNode=window.asmDomHelpers.domApi.createTextNode;c.createComment=window.asmDomHelpers.domApi.createComment;
c.createDocumentFragment=window.asmDomHelpers.domApi.createDocumentFragment;c.insertBefore=window.asmDomHelpers.domApi.insertBefore;c.removeChild=window.asmDomHelpers.domApi.removeChild;c.appendChild=window.asmDomHelpers.domApi.appendChild;c.removeAttribute=window.asmDomHelpers.domApi.removeAttribute;c.setAttribute=window.asmDomHelpers.domApi.setAttribute;c.parentNode=window.asmDomHelpers.domApi.parentNode;c.nextSibling=window.asmDomHelpers.domApi.nextSibling;c.F=window.asmDomHelpers.domApi.setNodeValue;
c.f=window.asmDomHelpers.nodes;c.h=window.asmDomHelpers.eventProxy}];E=1024;F=E+13376;za.push({m:function(){Ia()}},{m:function(){Ja()}});c.STATIC_BASE=E;c.STATIC_BUMP=13376;var Ka=F;F+=16;function La(){return!!La.b}var L=0;function M(){L+=4;return C[L-4>>2]}var Ma={};
function N(a,b){L=b;try{var d=M(),e=M(),f=M();a=0;N.b||(N.b=[null,[],[]],N.w=function(a,b){var d=N.b[a];assert(d);0===b||10===b?((1===a?c.print:c.printErr)(ia(d,0)),d.length=0):d.push(b)});for(b=0;b<f;b++){for(var h=C[e+8*b>>2],g=C[e+(8*b+4)>>2],k=0;k<g;k++)N.w(d,A[h+k]);a+=g}return a}catch(m){return"undefined"!==typeof FS&&m instanceof FS.j||y(m),-m.l}}function Na(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}
var Oa=void 0;function O(a){for(var b="";A[a];)b+=Oa[A[a++]];return b}var P={},R={},Pa={};function Qa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ra(a,b){a=Qa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Sa(a){var b=Error,d=Ra(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});d.prototype=Object.create(b.prototype);d.prototype.constructor=d;d.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return d}var Ta=void 0;function S(a){throw new Ta(a);}var Ua=void 0;
function Va(a,b){var d=[];function e(a){a=b(a);if(a.length!==d.length)throw new Ua("Mismatched type converter count");for(var e=0;e<d.length;++e)T(d[e],a[e])}d.forEach(function(b){Pa[b]=a});var f=Array(a.length),h=[],g=0;a.forEach(function(a,b){R.hasOwnProperty(a)?f[b]=R[a]:(h.push(a),P.hasOwnProperty(a)||(P[a]=[]),P[a].push(function(){f[b]=R[a];++g;g===h.length&&e(f)}))});0===h.length&&e(f)}
function T(a,b,d){d=d||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||S('type "'+e+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(d.C)return;S("Cannot register type '"+e+"' twice")}R[a]=b;delete Pa[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(function(a){a()}))}var Xa=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Ya(a){4<a&&0===--V[a].i&&(V[a]=void 0,Xa.push(a))}function W(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Xa.length?Xa.pop():V.length;V[b]={i:1,value:a};return b}}function Za(a){return this.fromWireType(D[a>>2])}function $a(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function ab(a,b){switch(b){case 2:return function(a){return this.fromWireType(ma[a>>2])};case 3:return function(a){return this.fromWireType(na[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}function bb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var d=Ra(b.name||"unknownFunctionName",function(){});d.prototype=b.prototype;d=new d;a=b.apply(d,a);return a instanceof Object?a:d}
function cb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function db(a,b){var d=c;if(void 0===d[a].a){var e=d[a];d[a]=function(){d[a].a.hasOwnProperty(arguments.length)||S("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+d[a].a+")!");return d[a].a[arguments.length].apply(this,arguments)};d[a].a=[];d[a].a[e.o]=e}}
function eb(a,b,d){c.hasOwnProperty(a)?((void 0===d||void 0!==c[a].a&&void 0!==c[a].a[d])&&S("Cannot register public name '"+a+"' twice"),db(a,a),c.hasOwnProperty(d)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+d+")!"),c[a].a[d]=b):(c[a]=b,void 0!==d&&(c[a].I=d))}function gb(a,b){for(var d=[],e=0;e<a;e++)d.push(C[(b>>2)+e]);return d}
function hb(a,b){a=O(a);if(void 0!==c["FUNCTION_TABLE_"+a])var d=c["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)d=FUNCTION_TABLE[b];else{d=c.asm["dynCall_"+a];void 0===d&&(d=c.asm["dynCall_"+a.replace(/f/g,"d")],void 0===d&&S("No dynCall invoker for signature: "+a));for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";d=(new Function("dynCall",
"rawFunction",f+"};\n"))(d,b)}"function"!==typeof d&&S("unknown function pointer with signature "+a+": "+b);return d}var ib=void 0;function jb(a){a=kb(a);var b=O(a);X(a);return b}function lb(a,b){function d(a){f[a]||R[a]||(Pa[a]?Pa[a].forEach(d):(e.push(a),f[a]=!0))}var e=[],f={};b.forEach(d);throw new ib(a+": "+e.map(jb).join([", "]));}
function mb(a,b,d){switch(b){case 0:return d?function(a){return z[a]}:function(a){return A[a]};case 1:return d?function(a){return B[a>>1]}:function(a){return la[a>>1]};case 2:return d?function(a){return C[a>>2]}:function(a){return D[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Y(a){a||S("Cannot use deleted val. handle = "+a);return V[a].value}function nb(a,b){var d=R[a];void 0===d&&S(b+" has unknown type "+jb(a));return d}var ob={};
function pb(a){var b=ob[a];return void 0===b?O(a):b}var qb=[];function rb(a){var b=qb.length;qb.push(a);return b}function sb(a,b){for(var d=Array(a),e=0;e<a;++e)d[e]=nb(C[(b>>2)+e],"parameter "+e);return d}var tb={},ub=1;function Z(a,b){Z.b||(Z.b={});a in Z.b||(c.dynCall_v(b),Z.b[a]=1)}for(var vb=Array(256),wb=0;256>wb;++wb)vb[wb]=String.fromCharCode(wb);Oa=vb;Ta=c.BindingError=Sa("BindingError");Ua=c.InternalError=Sa("InternalError");
c.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};c.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};ib=c.UnboundTypeError=Sa("UnboundTypeError");assert(!pa);var xb=F;F=F+4+15&-16;ua=xb;qa=ra=da(F);sa=qa+xa;ta=da(sa);C[ua>>2]=ta;pa=!0;c.wasmTableSize=158;c.wasmMaxTableSize=158;c.u={};
c.v={abort:y,enlargeMemory:function(){va()},getTotalMemory:function(){return G},abortOnCannotGrowMemory:va,___cxa_allocate_exception:function(a){return yb(a)},___cxa_throw:function(a){"uncaught_exception"in La?La.b++:La.b=1;throw a+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},___setErrNo:function(a){c.___errno_location&&(C[c.___errno_location()>>2]=a);return a},___syscall140:function(a,
b){L=b;try{var d=Ma.A();M();var e=M(),f=M(),h=M();FS.H(d,e,h);C[f>>2]=d.position;d.B&&0===e&&0===h&&(d.B=null);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof FS.j||y(g),-g.l}},___syscall146:N,___syscall6:function(a,b){L=b;try{var d=Ma.A();FS.close(d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.j||y(e),-e.l}},__embind_register_bool:function(a,b,d,e,f){var h=Na(d);b=O(b);T(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?e:f},argPackAdvance:8,
readValueFromPointer:function(a){if(1===d)var e=z;else if(2===d)e=B;else if(4===d)e=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>h])},c:null})},__embind_register_emval:function(a,b){b=O(b);T(a,{name:b,fromWireType:function(a){var b=V[a].value;Ya(a);return b},toWireType:function(a,b){return W(b)},argPackAdvance:8,readValueFromPointer:Za,c:null})},__embind_register_float:function(a,b,d){d=Na(d);b=O(b);T(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,
b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+$a(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:ab(b,d),c:null})},__embind_register_function:function(a,b,d,e,f,h){var g=gb(b,d);a=O(a);f=hb(e,f);eb(a,function(){lb("Cannot call "+a+" due to unbound types",g)},b-1);Va(g,function(d){var e=[d[0],null].concat(d.slice(1)),g=d=a,k=f,p=e.length;2>p&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var wa=
null!==e[1]&&!1,U=!1,l=1;l<e.length;++l)if(null!==e[l]&&void 0===e[l].c){U=!0;break}var Wa="void"!==e[0].name,K="",Q="";for(l=0;l<p-2;++l)K+=(0!==l?", ":"")+"arg"+l,Q+=(0!==l?", ":"")+"arg"+l+"Wired";g="return function "+Qa(g)+"("+K+") {\nif (arguments.length !== "+(p-2)+") {\nthrowBindingError('function "+g+" called with ' + arguments.length + ' arguments, expected "+(p-2)+" args!');\n}\n";U&&(g+="var destructors = [];\n");var fb=U?"destructors":"null";K="throwBindingError invoker fn runDestructors retType classParam".split(" ");
k=[S,k,h,cb,e[0],e[1]];wa&&(g+="var thisWired = classParam.toWireType("+fb+", this);\n");for(l=0;l<p-2;++l)g+="var arg"+l+"Wired = argType"+l+".toWireType("+fb+", arg"+l+"); // "+e[l+2].name+"\n",K.push("argType"+l),k.push(e[l+2]);wa&&(Q="thisWired"+(0<Q.length?", ":"")+Q);g+=(Wa?"var rv = ":"")+"invoker(fn"+(0<Q.length?", ":"")+Q+");\n";if(U)g+="runDestructors(destructors);\n";else for(l=wa?1:2;l<e.length;++l)p=1===l?"thisWired":"arg"+(l-2)+"Wired",null!==e[l].c&&(g+=p+"_dtor("+p+"); // "+e[l].name+
"\n",K.push(p+"_dtor"),k.push(e[l].c));Wa&&(g+="var ret = retType.fromWireType(rv);\nreturn ret;\n");K.push(g+"}\n");e=bb(K).apply(null,k);l=b-1;if(!c.hasOwnProperty(d))throw new Ua("Replacing nonexistant public symbol");void 0!==c[d].a&&void 0!==l?c[d].a[l]=e:(c[d]=e,c[d].o=l);return[]})},__embind_register_integer:function(a,b,d,e,f){function h(a){return a}b=O(b);-1===f&&(f=4294967295);var g=Na(d);if(0===e){var k=32-8*d;h=function(a){return a<<k>>>k}}var m=-1!=b.indexOf("unsigned");T(a,{name:b,fromWireType:h,
toWireType:function(a,d){if("number"!==typeof d&&"boolean"!==typeof d)throw new TypeError('Cannot convert "'+$a(d)+'" to '+this.name);if(d<e||d>f)throw new TypeError('Passing a number "'+$a(d)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return m?d>>>0:d|0},argPackAdvance:8,readValueFromPointer:mb(b,g,0!==e),c:null})},__embind_register_memory_view:function(a,b,d){function e(a){a>>=2;var b=D;return new f(b.buffer,b[a+1],b[a])}var f=
[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];d=O(d);T(a,{name:d,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{C:!0})},__embind_register_std_string:function(a,b){b=O(b);T(a,{name:b,fromWireType:function(a){for(var b=D[a>>2],d=Array(b),h=0;h<b;++h)d[h]=String.fromCharCode(A[a+4+h]);X(a);return d.join("")},toWireType:function(a,b){function d(a,b){return a[b]}function e(a,b){return a.charCodeAt(b)}b instanceof ArrayBuffer&&(b=new Uint8Array(b));
var g;b instanceof Uint8Array?g=d:b instanceof Uint8ClampedArray?g=d:b instanceof Int8Array?g=d:"string"===typeof b?g=e:S("Cannot pass non-string to std::string");var k=b.length,m=yb(4+k);D[m>>2]=k;for(var r=0;r<k;++r){var w=g(b,r);255<w&&(X(m),S("String has UTF-16 code units that do not fit in 8 bits"));A[m+4+r]=w}null!==a&&a.push(X,m);return m},argPackAdvance:8,readValueFromPointer:Za,c:function(a){X(a)}})},__embind_register_std_wstring:function(a,b,d){d=O(d);if(2===b){var e=function(){return la};
var f=1}else 4===b&&(e=function(){return D},f=2);T(a,{name:d,fromWireType:function(a){for(var b=e(),d=D[a>>2],h=Array(d),r=a+4>>f,w=0;w<d;++w)h[w]=String.fromCharCode(b[r+w]);X(a);return h.join("")},toWireType:function(a,d){var g=e(),h=d.length,r=yb(4+h*b);D[r>>2]=h;for(var w=r+4>>f,p=0;p<h;++p)g[w+p]=d.charCodeAt(p);null!==a&&a.push(X,r);return r},argPackAdvance:8,readValueFromPointer:Za,c:function(a){X(a)}})},__embind_register_void:function(a,b){b=O(b);T(a,{D:!0,name:b,argPackAdvance:0,fromWireType:function(){},
toWireType:function(){}})},__emval_as:function(a,b,d){a=Y(a);b=nb(b,"emval::as");var e=[],f=W(e);C[d>>2]=f;return b.toWireType(e,a)},__emval_call_method:function(a,b,d,e,f){a=qb[a];b=Y(b);d=pb(d);var h=[];C[e>>2]=W(h);return a(b,d,h,f)},__emval_decref:Ya,__emval_get_global:function(a){if(0===a)return W(Function("return this")());a=pb(a);return W(Function("return this")()[a])},__emval_get_method_caller:function(a,b){b=sb(a,b);for(var d=b[0],e=d.name+"_$"+b.slice(1).map(function(a){return a.name}).join("_")+
"$",f=["retType"],h=[d],g="",k=0;k<a-1;++k)g+=(0!==k?", ":"")+"arg"+k,f.push("argType"+k),h.push(b[1+k]);e="return function "+Qa("methodCaller_"+e)+"(handle, name, destructors, args) {\n";var m=0;for(k=0;k<a-1;++k)e+="    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[k+1].argPackAdvance;e+="    var rv = handle[name]("+g+");\n";for(k=0;k<a-1;++k)b[k+1].deleteObject&&(e+="    argType"+k+".deleteObject(arg"+k+");\n");d.D||(e+="    return retType.toWireType(destructors, rv);\n");
f.push(e+"};\n");a=bb(f).apply(null,h);return rb(a)},__emval_get_property:function(a,b){a=Y(a);b=Y(b);return W(a[b])},__emval_incref:function(a){4<a&&(V[a].i+=1)},__emval_new_cstring:function(a){return W(pb(a))},__emval_run_destructors:function(a){cb(V[a].value);Ya(a)},__emval_set_property:function(a,b,d){a=Y(a);b=Y(b);d=Y(d);a[b]=d},__emval_strictly_equals:function(a,b){a=Y(a);b=Y(b);return a===b},__emval_take_value:function(a,b){a=nb(a,"_emval_take_value");a=a.readValueFromPointer(b);return W(a)},
_abort:function(){c.abort()},_emscripten_asm_const_i:function(a){return Ha[a]()},_emscripten_asm_const_ii:function(a,b){return Ha[a](b)},_emscripten_asm_const_iii:function(a,b,d){return Ha[a](b,d)},_emscripten_asm_const_iiii:function(a,b,d,e){return Ha[a](b,d,e)},_emscripten_memcpy_big:function(a,b,d){A.set(A.subarray(b,b+d),a);return a},_pthread_getspecific:function(a){return tb[a]||0},_pthread_key_create:function(a){if(0==a)return 22;C[a>>2]=ub;tb[ub]=0;ub++;return 0},_pthread_once:Z,_pthread_setspecific:function(a,
b){if(!(a in tb))return 22;tb[a]=b;return 0},DYNAMICTOP_PTR:ua,tempDoublePtr:Ka,STACKTOP:ra};var zb=c.asm(c.u,c.v,buffer);c.asm=zb;var Ia=c.__GLOBAL__sub_I_asm_dom_cpp=function(){return c.asm.__GLOBAL__sub_I_asm_dom_cpp.apply(null,arguments)},Ja=c.__GLOBAL__sub_I_bind_cpp=function(){return c.asm.__GLOBAL__sub_I_bind_cpp.apply(null,arguments)};c.___errno_location=function(){return c.asm.___errno_location.apply(null,arguments)};
var kb=c.___getTypeName=function(){return c.asm.___getTypeName.apply(null,arguments)},X=c._free=function(){return c.asm._free.apply(null,arguments)};c._main=function(){return c.asm._main.apply(null,arguments)};var yb=c._malloc=function(){return c.asm._malloc.apply(null,arguments)},ka=c.stackAlloc=function(){return c.asm.stackAlloc.apply(null,arguments)};c.dynCall_ii=function(){return c.asm.dynCall_ii.apply(null,arguments)};c.dynCall_iii=function(){return c.asm.dynCall_iii.apply(null,arguments)};
c.dynCall_iiii=function(){return c.asm.dynCall_iiii.apply(null,arguments)};c.dynCall_iiiii=function(){return c.asm.dynCall_iiiii.apply(null,arguments)};c.dynCall_v=function(){return c.asm.dynCall_v.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.dynCall_vi.apply(null,arguments)};c.dynCall_vii=function(){return c.asm.dynCall_vii.apply(null,arguments)};c.dynCall_viiii=function(){return c.asm.dynCall_viiii.apply(null,arguments)};
c.dynCall_viiiii=function(){return c.asm.dynCall_viiiii.apply(null,arguments)};c.dynCall_viiiiii=function(){return c.asm.dynCall_viiiiii.apply(null,arguments)};c.asm=zb;c.UTF8ToString=function(a){return ia(A,a)};function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}x.prototype=Error();x.prototype.constructor=x;J=function Ab(){c.calledRun||Bb();c.calledRun||(J=Ab)};
c.callMain=function(a){a=a||[];Da||(Da=!0,H(za));var b=a.length+1,d=ka(4*(b+1));C[d>>2]=ja(c.thisProgram);for(var e=1;e<b;e++)C[(d>>2)+e]=ja(a[e-1]);C[(d>>2)+b]=0;try{var f=c._main(b,d,0);Cb(f,!0)}catch(h){h instanceof x||("SimulateInfiniteLoop"==h?c.noExitRuntime=!0:((a=h)&&"object"===typeof h&&h.stack&&(a=[h,h.stack]),c.printErr("exception thrown: "+a),c.quit(1,h)))}finally{}};
function Bb(a){function b(){if(!c.calledRun&&(c.calledRun=!0,!fa)){Da||(Da=!0,H(za));H(Aa);if(c.onRuntimeInitialized)c.onRuntimeInitialized();c._main&&Db&&c.callMain(a);if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var b=c.postRun.shift();Ca.unshift(b)}H(Ca)}}a=a||c.arguments;if(!(0<I)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ea();H(ya);0<I||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);b()},1)):b())}}c.run=Bb;function Cb(a,b){if(!b||!c.noExitRuntime||0!==a){if(!c.noExitRuntime&&(fa=!0,ra=void 0,H(Ba),c.onExit))c.onExit(a);v&&process.exit(a);c.quit(a,new x(a))}}c.exit=Cb;function y(a){if(c.onAbort)c.onAbort(a);void 0!==a?(c.print(a),c.printErr(a),a=JSON.stringify(a)):a="";fa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=y;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var Db=!0;
c.noInitialRun&&(Db=!1);c.noExitRuntime=!0;Bb();
