var emscripten = function(emscripten) {
  emscripten = emscripten || {};

var e;e||(e=typeof emscripten !== 'undefined' ? emscripten : {});e.ma||(e.ma=0,e.sb=0);e.ma++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var f=b;c.total&&(f=c.total);if(c.loaded){d.i?e.M[a].loaded=c.loaded:(d.i=!0,e.M||(e.M={}),e.M[a]={loaded:c.loaded,total:f});var g=f=c=0,h;for(h in e.M){var l=e.M[h];c+=l.total;f+=l.loaded;g++}c=Math.ceil(c*e.ma/g);e.setStatus&&e.setStatus("Downloading data... ("+f+"/"+c+")")}else!e.M&&e.setStatus&&e.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(){function b(a,b,c,d){this.start=a;this.end=b;this.qb=c;this.audio=d}function c(c){e.sb++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);b.prototype.nb=c;c=a.files;for(var d=0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();
e.removeRunDependency("datafile_text.data")}e.FS_createPath("/","examples",!0,!0);e.FS_createPath("/examples","assets",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;e.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.nb.subarray(this.start,this.end))},finish:function(a){e.FS_createDataFile(this.name,null,a,!0,!0,!0);e.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,f=0;f<d.length;++f)(new b(d[f].start,
d[f].end,d[f].qb,d[f].audio)).open("GET",d[f].filename);e.addRunDependency("datafile_text.data");e.Wa||(e.Wa={});e.Wa["text.data"]={Xd:!1};h?(c(h),h=null):g=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof e.locateFilePackage||e.locateFile||(e.locateFile=e.locateFilePackage,e.printErr("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var d="function"===typeof e.locateFile?e.locateFile("text.data"):(e.filePackagePrefixURL||"")+"text.data",f=a.fe,g=null,h=e.getPreloadedPackage?e.getPreloadedPackage(d,f):null;h||b(d,f,function(a){g?(g(a),g=null):h=a});e.calledRun?c():(e.preRun||(e.preRun=[]),e.preRun.push(c))})({files:[{audio:0,
start:0,crunched:0,end:325,filename:"/examples/assets/CMakeLists.txt"},{audio:0,start:325,crunched:0,end:4702,filename:"/examples/assets/InTheCube_hero.png"},{audio:0,start:4702,crunched:0,end:301414,filename:"/examples/assets/arial.ttf"},{audio:0,start:301414,crunched:0,end:301644,filename:"/examples/assets/asset.hpp.in"},{audio:1,start:301644,crunched:0,end:734130,filename:"/examples/assets/water.mp3"}],remote_package_size:734130,package_uuid:"7d647a99-9825-4e34-9b59-abb2a864dc57"});var aa={},k;
for(k in e)e.hasOwnProperty(k)&&(aa[k]=e[k]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var ba=!1,m=!1,n=!1,ca=!1;
if(e.ENVIRONMENT)if("WEB"===e.ENVIRONMENT)ba=!0;else if("WORKER"===e.ENVIRONMENT)m=!0;else if("NODE"===e.ENVIRONMENT)n=!0;else if("SHELL"===e.ENVIRONMENT)ca=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else ba="object"===typeof window,m="function"===typeof importScripts,n="object"===typeof process&&"function"===typeof require&&!ba&&!m,ca=!ba&&!n&&!m;
if(n){var da,ea;e.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;});process.on("unhandledRejection",function(){process.exit(1)});e.inspect=
function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(ba||m)e.read=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},m&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};else throw Error("not compiled for this environment");
e.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;e.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||e.print;e.print=e.print;e.printErr=e.printErr;for(k in aa)aa.hasOwnProperty(k)&&(e[k]=aa[k]);aa=void 0;function ha(a){assert(!ia);var b=p;p=p+a+15&-16;return b}function ja(a){var b;b||(b=16);return Math.ceil(a/b)*b}
function ka(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:return"*"===a[a.length-1]?4:"i"===a[0]?(a=parseInt(a.substr(1)),assert(0===a%8),a/8):0}}function la(a){ma||(ma={});ma[a]||(ma[a]=1,e.printErr(a))}var ma,na={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},oa=0;function assert(a,b){a||t("Assertion failed: "+b)}
function pa(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":v[a>>0]=b;break;case "i8":v[a>>0]=b;break;case "i16":qa[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":tempI64=[b>>>0,(tempDouble=b,1<=+ra(tempDouble)?0<tempDouble?(sa(+ua(tempDouble/4294967296),4294967295)|0)>>>0:~~+va((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];w[a>>2]=tempI64[0];w[a+4>>2]=tempI64[1];break;case "float":x[a>>2]=b;break;case "double":wa[a>>3]=b;break;default:t("invalid type for setValue: "+
c)}}function y(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;var f="string"===typeof b?b:null;var g=("function"===typeof xa?xa:ha)(Math.max(d,f?1:b.length));if(c){a=g;assert(0==(g&3));for(b=g+(d&-4);a<b;a+=4)w[a>>2]=0;for(b=g+d;a<b;)v[a++>>0]=0;return g}if("i8"===f)return a.subarray||a.slice?A.set(a,g):A.set(new Uint8Array(a),g),g;c=0;for(var h,l,q;c<d;){var r=a[c];h=f||b[c];0===h?c++:("i64"==h&&(h="i32"),pa(g+c,r,h),q!==h&&(l=ka(h),q=h),c+=l)}return g}
function ya(a){if(ia)if(za)var b=xa(a);else assert(B),b=w[B>>2],a=b+a+15&-16,w[B>>2]=a,a>=C&&!Aa()&&(w[B>>2]=b,b=0);else b=ha(a);return b}function D(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=A[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,A.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return Ba(A,a)}var Ca="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ba(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&Ca)return Ca.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var l=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|l;else{var q=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|l<<6|q}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function Da(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=128|
h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Fa(a){var b=Ea(a)+1,c=Ga(b);Da(a,v,c,b);return c}var Ha=65536,Ia=16777216,Ja=16777216;function Ka(a,b){0<a%b&&(a+=b-a%b);return a}
var buffer,v,A,qa,La,w,Ma,x,wa;function Na(){e.HEAP8=v=new Int8Array(buffer);e.HEAP16=qa=new Int16Array(buffer);e.HEAP32=w=new Int32Array(buffer);e.HEAPU8=A=new Uint8Array(buffer);e.HEAPU16=La=new Uint16Array(buffer);e.HEAPU32=Ma=new Uint32Array(buffer);e.HEAPF32=x=new Float32Array(buffer);e.HEAPF64=wa=new Float64Array(buffer)}var Oa,p,ia,Pa,Qa,Ra,Sa,B;Oa=p=Pa=Qa=Ra=Sa=B=0;ia=!1;
e.reallocBuffer||(e.reallocBuffer=function(a){try{if(ArrayBuffer.Nb)var b=ArrayBuffer.Nb(buffer,a);else{var c=v;b=new ArrayBuffer(a);(new Int8Array(b)).set(c)}}catch(d){return!1}return Ta(b)?b:!1});function Aa(){var a=e.usingWasm?Ha:Ia,b=2147483648-a;if(w[B>>2]>b)return!1;var c=C;for(C=Math.max(C,Ja);C<w[B>>2];)536870912>=C?C=Ka(2*C,a):C=Math.min(Ka((3*C+2147483648)/4,a),b);a=e.reallocBuffer(C);if(!a||a.byteLength!=C)return C=c,!1;e.buffer=buffer=a;Na();return!0}var Ua;
try{Ua=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Ua(new ArrayBuffer(4))}catch(a){Ua=function(b){return b.byteLength}}var Va=e.TOTAL_STACK||5242880,C=e.TOTAL_MEMORY||16777216;C<Va&&e.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+C+"! (TOTAL_STACK="+Va+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:C/Ha}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(C),e.buffer=buffer);Na();w[0]=1668509029;qa[1]=25459;if(115!==A[2]||99!==A[3])throw"Runtime error: expected the system to be little-endian!";
function Wa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.J;"number"===typeof c?void 0===b.X?e.dynCall_v(c):e.dynCall_vi(c,b.X):c(void 0===b.X?null:b.X)}}}var Xa=[],Ya=[],Za=[],$a=[],ab=[],za=!1;function bb(){var a=e.preRun.shift();Xa.unshift(a)}var ra=Math.abs,va=Math.ceil,ua=Math.floor,sa=Math.min,cb=Math.clz32,db=0,eb=null,fb=null;function gb(){db++;e.monitorRunDependencies&&e.monitorRunDependencies(db)}
function hb(){db--;e.monitorRunDependencies&&e.monitorRunDependencies(db);if(0==db&&(null!==eb&&(clearInterval(eb),eb=null),fb)){var a=fb;fb=null;a()}}e.preloadedImages={};e.preloadedAudios={};function ib(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(u){t(u)}}function b(){return e.wasmBinary||!ba&&!m||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){l=a.exports;if(l.memory){a=l.memory;var b=e.buffer;a.byteLength<b.byteLength&&e.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;Na()}e.asm=l;e.usingWasm=!0;hb()}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a).catch(function(a){e.printErr("failed to asynchronously prepare wasm: "+
a);t(a)})}if("object"!==typeof WebAssembly)return e.printErr("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return e.printErr("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;gb();if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(Y){return e.printErr("Module.instantiateWasm callback failed with error: "+Y),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
ib(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d).catch(function(a){e.printErr("wasm streaming compile failed: "+a);e.printErr("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="text.wast",f="text.wasm",g="text.temp.asm.js";"function"===typeof e.locateFile&&(ib(d)||(d=e.locateFile(d)),ib(f)||(f=e.locateFile(f)),ib(g)||(g=e.locateFile(g)));var h={global:null,env:null,asm2wasm:na,parent:e},l=null;e.asmPreload=e.asm;
var q=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===r)var b=q(a);else a:{a=Ka(a,e.usingWasm?Ha:Ia);var c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(E){b=null;break a}b=void 0}return b};var r="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,
maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);assert(b,"no binaryen method succeeded.");return b}})();Oa=1024;p=Oa+132960;Ya.push({J:function(){jb()}},{J:function(){kb()}},{J:function(){lb()}},{J:function(){mb()}},{J:function(){nb()}},{J:function(){ob()}});e.STATIC_BASE=Oa;e.STATIC_BUMP=132960;var pb=p;p+=16;var F={};
function qb(a){if(qb.ob){var b=w[a>>2];var c=w[b>>2]}else qb.ob=!0,F.USER=F.LOGNAME="web_user",F.PATH="/",F.PWD="/",F.HOME="/home/web_user",F.LANG="C.UTF-8",F._=e.thisProgram,c=ya(1024),b=ya(256),w[b>>2]=c,w[a>>2]=b;a=[];var d=0,f;for(f in F)if("string"===typeof F[f]){var g=f+"="+F[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var h=c,l=0;l<d.length;++l)v[h++>>0]=d.charCodeAt(l);v[h>>0]=0;w[b+4*f>>2]=c;c+=g.length+
1}w[b+4*a.length>>2]=0}var rb=0,sb=[],tb={};function ub(){var a=rb;if(!a)return(vb(0),0)|0;var b=tb[a],c=b.type;if(!c)return(vb(0),a)|0;var d=Array.prototype.slice.call(arguments);e.___cxa_is_pointer_type(c);ub.buffer||(ub.buffer=xa(4));w[ub.buffer>>2]=a;a=ub.buffer;for(var f=0;f<d.length;f++)if(d[f]&&e.___cxa_can_catch(d[f],c,a))return a=w[a>>2],b.Ba=a,(vb(d[f]),a)|0;a=w[a>>2];return(vb(c),a)|0}
var G={H:1,B:2,Dd:3,yc:4,F:5,Aa:6,Rb:7,Wc:8,A:9,ec:10,va:11,Nd:11,gb:12,fa:13,rc:14,jd:15,ga:16,wa:17,Od:18,ia:19,ya:20,P:21,h:22,Rc:23,fb:24,G:25,Kd:26,sc:27,dd:28,W:29,Ad:30,Kc:31,td:32,oc:33,xd:34,$c:42,vc:43,fc:44,Bc:45,Cc:46,Dc:47,Jc:48,Ld:49,Uc:50,Ac:51,lc:35,Xc:37,Xb:52,$b:53,Pd:54,Sc:55,ac:56,bc:57,mc:35,cc:59,gd:60,Vc:61,Hd:62,ed:63,ad:64,bd:65,zd:66,Yc:67,Ub:68,Ed:69,hc:70,ud:71,Mc:72,pc:73,Zb:74,od:76,Yb:77,yd:78,Ec:79,Fc:80,Ic:81,Hc:82,Gc:83,hd:38,za:39,Nc:36,ha:40,pd:95,sd:96,kc:104,
Tc:105,Vb:97,wd:91,md:88,cd:92,Bd:108,jc:111,Sb:98,ic:103,Qc:101,Oc:100,Id:110,tc:112,uc:113,xc:115,Wb:114,nc:89,Lc:90,vd:93,Cd:94,Tb:99,Pc:102,zc:106,kd:107,Jd:109,Md:87,qc:122,Fd:116,nd:95,Zc:123,wc:84,qd:75,dc:125,ld:131,rd:130,Gd:86};function wb(a){e.___errno_location&&(w[e.___errno_location()>>2]=a);return a}
var xb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",
24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",
44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",
65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",
82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",
100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",
122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function yb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function zb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=yb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ab(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Bb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Cb(){var a=Array.prototype.slice.call(arguments,0);return zb(a.join("/"))}function H(a,b){return zb(a+"/"+b)}
function Db(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=yb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var Eb=[];function Fb(a,b){Eb[a]={input:[],output:[],O:b};Gb(a,Hb)}
var Hb={open:function(a){var b=Eb[a.node.rdev];if(!b)throw new I(G.ia);a.tty=b;a.seekable=!1},close:function(a){a.tty.O.flush(a.tty)},flush:function(a){a.tty.O.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.O.Oa)throw new I(G.Aa);for(var f=0,g=0;g<d;g++){try{var h=a.tty.O.Oa(a.tty)}catch(l){throw new I(G.F);}if(void 0===h&&0===f)throw new I(G.va);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.O.ta)throw new I(G.Aa);
for(var f=0;f<d;f++)try{a.tty.O.ta(a.tty,b[c+f])}catch(g){throw new I(G.F);}d&&(a.node.timestamp=Date.now());return f}},Ib={Oa:function(a){if(!a.input.length){var b=null;if(n){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=J(b,!0)}return a.input.shift()},ta:function(a,b){null===b||10===b?(e.print(Ba(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(e.print(Ba(a.output,0)),a.output=[])}},Jb={ta:function(a,b){null===b||10===b?(e.printErr(Ba(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(e.printErr(Ba(a.output,0)),a.output=[])}},K={s:null,m:function(){return K.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(G.H);K.s||(K.s={dir:{node:{v:K.c.v,l:K.c.l,lookup:K.c.lookup,T:K.c.T,rename:K.c.rename,unlink:K.c.unlink,rmdir:K.c.rmdir,readdir:K.c.readdir,symlink:K.c.symlink},stream:{C:K.f.C}},file:{node:{v:K.c.v,l:K.c.l},stream:{C:K.f.C,read:K.f.read,write:K.f.write,Ca:K.f.Ca,Sa:K.f.Sa,aa:K.f.aa}},link:{node:{v:K.c.v,
l:K.c.l,readlink:K.c.readlink},stream:{}},Ha:{node:{v:K.c.v,l:K.c.l},stream:Kb}});c=Lb(a,b,c,d);L(c.mode)?(c.c=K.s.dir.node,c.f=K.s.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=K.s.file.node,c.f=K.s.file.stream,c.g=0,c.b=null):40960===(c.mode&61440)?(c.c=K.s.link.node,c.f=K.s.link.stream):8192===(c.mode&61440)&&(c.c=K.s.Ha.node,c.f=K.s.Ha.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},ub:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.g;++c)b.push(a.b[c]);return b}return a.b},Zd:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array},Ja:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=K.ub(a),a.g=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(c.subarray(0,a.g),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Eb:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{v:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.I=4096;b.blocks=Math.ceil(b.size/b.I);return b},
l:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.Eb(a,b.size)},lookup:function(){throw Mb[G.B];},T:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(L(a.mode)){try{var d=Nb(b,c)}catch(g){}if(d)for(var f in d.b)throw new I(G.za);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=Nb(a,b),d;for(d in c.b)throw new I(G.za);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(G.h);return a.link}},f:{read:function(a,b,c,d,f){var g=a.node.b;if(f>=a.node.g)return 0;a=Math.min(a.node.g-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.g=d;if(0===a.g&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.g=d;if(f+d<=a.g)return a.b.set(b.subarray(c,c+d),f),d}K.Ja(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.g=Math.max(a.g,f+d);return d},C:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new I(G.h);return b},Ca:function(a,b,c){K.Ja(a.node,b+c);a.node.g=Math.max(a.node.g,
b+c)},Sa:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new I(G.ia);c=a.node.b;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.g)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=xa(d);if(!d)throw new I(G.gb);b.set(c,d)}else a=!1,d=c.byteOffset;return{Bb:d,kb:a}},aa:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new I(G.ia);if(f&2)return 0;K.f.write(a,b,0,d,c,!1);return 0}}},M={$:!1,Ib:function(){M.$=!!process.platform.match(/^win/);
var a=process.binding("constants");a.fs&&(a=a.fs);M.Ka={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Da:function(a){return Buffer.i?Buffer.from(a):new Buffer(a)},m:function(a){assert(n);return M.createNode(null,"/",M.Na(a.sa.root),0)},createNode:function(a,b,c){if(!L(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new I(G.h);a=Lb(a,b,c);a.c=M.c;a.f=M.f;return a},Na:function(a){try{var b=fs.lstatSync(a);M.$&&(b.mode=b.mode|(b.mode&292)>>
2)}catch(c){if(!c.code)throw c;throw new I(G[c.code]);}return b.mode},o:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.m.sa.root);b.reverse();return Cb.apply(null,b)},tb:function(a){a&=-2656257;var b=0,c;for(c in M.Ka)a&c&&(b|=M.Ka[c],a^=c);if(a)throw new I(G.h);return b},c:{v:function(a){a=M.o(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new I(G[c.code]);}M.$&&!b.I&&(b.I=4096);M.$&&!b.blocks&&(b.blocks=(b.size+b.I-1)/b.I|0);return{dev:b.dev,ino:b.ino,
mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,I:b.I,blocks:b.blocks}},l:function(a,b){var c=M.o(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new I(G[d.code]);}},lookup:function(a,b){var c=H(M.o(a),b);c=M.Na(c);return M.createNode(a,b,c)},T:function(a,b,c,d){a=M.createNode(a,b,c,d);b=M.o(a);try{L(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,
"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new I(G[f.code]);}return a},rename:function(a,b,c){a=M.o(a);b=H(M.o(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new I(G[d.code]);}},unlink:function(a,b){a=H(M.o(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new I(G[c.code]);}},rmdir:function(a,b){a=H(M.o(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new I(G[c.code]);}},readdir:function(a){a=M.o(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;
throw new I(G[b.code]);}},symlink:function(a,b,c){a=H(M.o(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new I(G[d.code]);}},readlink:function(a){var b=M.o(a);try{return b=fs.readlinkSync(b),b=Pb.relative(Pb.resolve(a.m.sa.root),b)}catch(c){if(!c.code)throw c;throw new I(G[c.code]);}}},f:{open:function(a){var b=M.o(a.node);try{32768===(a.node.mode&61440)&&(a.V=fs.openSync(b,M.tb(a.flags)))}catch(c){if(!c.code)throw c;throw new I(G[c.code]);}},close:function(a){try{32768===(a.node.mode&
61440)&&a.V&&fs.closeSync(a.V)}catch(b){if(!b.code)throw b;throw new I(G[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.V,M.Da(b.buffer),c,d,f)}catch(g){throw new I(G[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.V,M.Da(b.buffer),c,d,f)}catch(g){throw new I(G[g.code]);}},C:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.V).size}catch(d){throw new I(G[d.code]);}if(0>b)throw new I(G.h);return b}}};
p+=16;p+=16;p+=16;var Qb=null,Rb={},Sb=[],Tb=1,Ub=null,Vb=!0,Wb={},I=null,Mb={};
function N(a,b){a=Db("/",a);b=b||{};if(!a)return{path:"",node:null};var c={La:!0,ua:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ua)throw new I(G.ha);a=yb(a.split("/").filter(function(a){return!!a}),!1);var f=Qb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Nb(f,a[d]);c=H(c,a[d]);f.U&&(!g||g&&b.La)&&(f=f.U.root);if(!g||b.na)for(g=0;40960===(f.mode&61440);)if(f=Xb(c),c=Db(Ab(c),f),f=N(c,{ua:b.ua}).node,40<g++)throw new I(G.ha);}return{path:c,node:f}}
function Yb(a){for(var b;;){if(a===a.parent)return a=a.m.Ta,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ub.length}function $b(a){var b=Zb(a.parent.id,a.name);a.N=Ub[b];Ub[b]=a}function Nb(a,b){var c;if(c=(c=ac(a,"x"))?c:a.c.lookup?0:G.fa)throw new I(c,a);for(c=Ub[Zb(a.id,b)];c;c=c.N){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function Lb(a,b,c,d){bc||(bc=function(a,b,c,d){a||(a=this);this.parent=a;this.m=a.m;this.U=null;this.id=Tb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},bc.prototype={},Object.defineProperties(bc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},zb:{get:function(){return L(this.mode)}},yb:{get:function(){return 8192===(this.mode&
61440)}}}));a=new bc(a,b,c,d);$b(a);return a}function L(a){return 16384===(a&61440)}var cc={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function dc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function ac(a,b){if(Vb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return G.fa}else return G.fa;return 0}
function ec(a,b){try{return Nb(a,b),G.wa}catch(c){}return ac(a,"wx")}function fc(a){var b=4096;for(a=a||0;a<=b;a++)if(!Sb[a])return a;throw new I(G.fb);}function hc(a,b){ic||(ic=function(){},ic.prototype={},Object.defineProperties(ic.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new ic,d;for(d in a)c[d]=a[d];a=c;b=fc(b);a.fd=b;return Sb[b]=a}var Kb={open:function(a){a.f=Rb[a.node.rdev].f;a.f.open&&a.f.open(a)},C:function(){throw new I(G.W);}};
function Gb(a,b){Rb[a]={f:b}}function jc(a,b){var c="/"===b,d=!b;if(c&&Qb)throw new I(G.ga);if(!c&&!d){var f=N(b,{La:!1});b=f.path;f=f.node;if(f.U)throw new I(G.ga);if(!L(f.mode))throw new I(G.ya);}b={type:a,sa:{},Ta:b,Ab:[]};a=a.m(b);a.m=b;b.root=a;c?Qb=a:f&&(f.U=b,f.m&&f.m.Ab.push(b))}function kc(a,b,c){var d=N(a,{parent:!0}).node;a=Bb(a);if(!a||"."===a||".."===a)throw new I(G.h);var f=ec(d,a);if(f)throw new I(f);if(!d.c.T)throw new I(G.H);return d.c.T(d,a,b,c)}
function O(a,b){return kc(a,(void 0!==b?b:511)&1023|16384,0)}function lc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return kc(a,b|8192,c)}function mc(a,b){if(!Db(a))throw new I(G.B);var c=N(b,{parent:!0}).node;if(!c)throw new I(G.B);b=Bb(b);var d=ec(c,b);if(d)throw new I(d);if(!c.c.symlink)throw new I(G.H);return c.c.symlink(c,b,a)}
function nc(a){var b=N(a,{parent:!0}).node,c=Bb(a),d=Nb(b,c);a:{try{var f=Nb(b,c)}catch(h){f=h.u;break a}var g=ac(b,"wx");f=g?g:L(f.mode)?G.P:0}if(f)throw new I(f);if(!b.c.unlink)throw new I(G.H);if(d.U)throw new I(G.ga);try{Wb.willDeletePath&&Wb.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.c.unlink(b,c);b=Zb(d.parent.id,d.name);if(Ub[b]===d)Ub[b]=d.N;else for(b=Ub[b];b;){if(b.N===d){b.N=d.N;break}b=b.N}try{if(Wb.onDeletePath)Wb.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Xb(a){a=N(a).node;if(!a)throw new I(G.B);if(!a.c.readlink)throw new I(G.h);return Db(Yb(a.parent),a.c.readlink(a))}function oc(a,b){var c;"string"===typeof a?c=N(a,{na:!0}).node:c=a;if(!c.c.l)throw new I(G.H);c.c.l(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function pc(a,b,c,d){if(""===a)throw new I(G.B);if("string"===typeof b){var f=cc[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=zb(a);try{g=N(a,{na:!(b&131072)}).node}catch(l){}}f=!1;if(b&64)if(g){if(b&128)throw new I(G.wa);}else g=kc(a,c,0),f=!0;if(!g)throw new I(G.B);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!L(g.mode))throw new I(G.ya);if(!f&&(c=g?40960===(g.mode&61440)?G.ha:
L(g.mode)&&("r"!==dc(b)||b&512)?G.P:ac(g,dc(b)):G.B))throw new I(c);if(b&512){c=g;var h;"string"===typeof c?h=N(c,{na:!0}).node:h=c;if(!h.c.l)throw new I(G.H);if(L(h.mode))throw new I(G.P);if(32768!==(h.mode&61440))throw new I(G.h);if(c=ac(h,"w"))throw new I(c);h.c.l(h,{size:0,timestamp:Date.now()})}b&=-641;d=hc({node:g,path:Yb(g),flags:b,seekable:!0,position:0,f:g.f,Ob:[],error:!1},d);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(qc||(qc={}),a in qc||(qc[a]=1,e.printErr("read file: "+a)));try{Wb.onOpenFile&&
(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Wb.onOpenFile(a,g))}catch(l){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function rc(a){if(null===a.fd)throw new I(G.A);a.pa&&(a.pa=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{Sb[a.fd]=null}a.fd=null}function sc(a,b,c){if(null===a.fd)throw new I(G.A);if(!a.seekable||!a.f.C)throw new I(G.W);a.position=a.f.C(a,b,c);a.Ob=[]}
function tc(a,b,c,d,f,g){if(0>d||0>f)throw new I(G.h);if(null===a.fd)throw new I(G.A);if(0===(a.flags&2097155))throw new I(G.A);if(L(a.node.mode))throw new I(G.P);if(!a.f.write)throw new I(G.h);a.flags&1024&&sc(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new I(G.W);b=a.f.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&Wb.onWriteToFile)Wb.onWriteToFile(a.path)}catch(l){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+l.message)}return b}
function uc(){I||(I=function(a,b){this.node=b;this.Hb=function(a){this.u=a;for(var b in G)if(G[b]===a){this.code=b;break}};this.Hb(a);this.message=xb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},I.prototype=Error(),I.prototype.constructor=I,[G.B].forEach(function(a){Mb[a]=new I(a);Mb[a].stack="<generic error, no stack>"}))}var vc;function wc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function xc(a,b,c,d){a=H("string"===typeof a?a:Yb(a),b);return O(a,wc(c,d))}function yc(a,b){a="string"===typeof a?a:Yb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=H(a,c);try{O(d)}catch(f){}a=d}}return d}function zc(a,b,c,d){a=H("string"===typeof a?a:Yb(a),b);c=wc(c,d);return kc(a,(void 0!==c?c:438)&4095|32768,0)}
function Ac(a,b,c,d,f,g){a=b?H("string"===typeof a?a:Yb(a),b):a;d=wc(d,f);f=kc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}oc(f,d|146);a=pc(f,"w");tc(a,c,0,c.length,0,g);rc(a);oc(f,d)}return f}
function P(a,b,c,d){a=H("string"===typeof a?a:Yb(a),b);b=wc(!!c,!!d);P.Ra||(P.Ra=64);var f=P.Ra++<<8|0;Gb(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,h=0;h<f;h++){try{var l=c()}catch(ta){throw new I(G.F);}if(void 0===l&&0===g)throw new I(G.va);if(null===l||void 0===l)break;g++;b[d+h]=l}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(u){throw new I(G.F);}f&&(a.node.timestamp=
Date.now());return g}});return lc(a,b,f)}function Bc(a,b,c){a=H("string"===typeof a?a:Yb(a),b);return mc(c,a)}
function Cc(a){if(a.yb||a.zb||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.b=J(e.read(a.url),!0),a.g=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||wb(G.F);return b}
function Dc(a,b,c,d,f){function g(){this.qa=!1;this.Y=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Pa(a/this.chunkSize|0)[b]}};g.prototype.Gb=function(a){this.Pa=a};g.prototype.Ea=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&"bytes"===
d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var h=this;h.Gb(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.Y[a]){var E=h.Y;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var l=new XMLHttpRequest;l.open("GET",c,!1);b!==g&&l.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(l.responseType="arraybuffer");l.overrideMimeType&&
l.overrideMimeType("text/plain; charset=x-user-defined");l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);d=void 0!==l.response?new Uint8Array(l.response||[]):J(l.responseText||"",!0);E[a]=d}if("undefined"===typeof h.Y[a])throw Error("doXHR failed!");return h.Y[a]});if(a||!b)g=b=1,g=b=this.Pa(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.jb=b;this.ib=g;this.qa=!0};if("undefined"!==
typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.qa||this.Ea();return this.jb}},chunkSize:{get:function(){this.qa||this.Ea();return this.ib}}});var l=void 0}else l=c,h=void 0;var q=zc(a,b,d,f);h?q.b=h:l&&(q.b=null,q.url=l);Object.defineProperties(q,{g:{get:function(){return this.b.length}}});var r={};Object.keys(q.f).forEach(function(a){var b=
q.f[a];r[a]=function(){if(!Cc(q))throw new I(G.F);return b.apply(null,arguments)}});r.read=function(a,b,c,d,f){if(!Cc(q))throw new I(G.F);a=a.node.b;if(f>=a.length)return 0;d=Math.min(a.length-f,d);assert(0<=d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};q.f=r;return q}
function Ec(a,b,c,d,f,g,h,l,q,r){function u(c){function E(c){r&&r();l||Ac(a,b,c,d,f,q);g&&g();hb()}var Y=!1;e.preloadPlugins.forEach(function(a){!Y&&a.canHandle(z)&&(a.handle(c,z,E,function(){h&&h();hb()}),Y=!0)});Y||E(c)}Fc();var z=b?Db(H(a,b)):a;gb();"string"==typeof c?Gc(c,function(a){u(a)},h):u(c)}var FS={},bc,ic,qc,Hc={},Q=0;function R(){Q+=4;return w[Q-4>>2]}function Ic(){var a=Sb[R()];if(!a)throw new I(G.A);return a}var Jc=0;function Kc(a,b){e.setThrew(a,b||1);throw"longjmp";}
var Lc=null,Mc="",Nc=0,Oc=null,Pc=0,Qc=0,Rc=0,Sc=0,Tc=[],Uc={},Vc,Wc,Xc,Yc=!1,Zc=!1,$c=[];
function Fc(){function a(){Zc=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!ad){ad=!0;try{bd=!0}catch(c){bd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}cd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:bd?null:console.log("warning: no BlobBuilder");
dd="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.Va||"undefined"!==typeof dd||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.Va=!0);e.preloadPlugins.push({canHandle:function(a){return!e.Va&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var c=null;if(bd)try{c=new Blob([a],{type:ed(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:ed(b)}))}catch(r){la("Blob constructor present but fails: "+
r+"; falling back to blob builder")}c||(c=new cd,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=dd.createObjectURL(c),q=new Image;q.onload=function(){assert(q.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=q.width;c.height=q.height;c.getContext("2d").drawImage(q,0,0);e.preloadedImages[b]=c;dd.revokeObjectURL(d);f&&f(a)};q.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};q.src=d}});e.preloadPlugins.push({canHandle:function(a){return!e.ee&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function c(c){q||(q=!0,e.preloadedAudios[b]=c,f&&f(a))}function d(){q||(q=!0,e.preloadedAudios[b]=new Audio,g&&g())}var q=!1;if(bd){try{var r=new Blob([a],{type:ed(b)})}catch(z){return d()}r=dd.createObjectURL(r);var u=new Audio;u.addEventListener("canplaythrough",function(){c(u)},!1);u.onerror=function(){if(!q){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",f=0,g=0,
h=0;h<a.length;h++)for(f=f<<8|a[h],g+=8;6<=g;){var l=f>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[l]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],d+="=");u.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(u)}};u.src=r;fd(function(){c(u)})}else return d()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(a){!Zc&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function gd(a,b,c,d){if(b&&e.L&&a==e.canvas)return e.L;if(b){var f={antialias:!1,alpha:!1};if(d)for(var g in d)f[g]=d[g];if(f=hd(a,f))var h=id[f].GLctx}else h=a.getContext("2d");if(!h)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.L=h,b&&jd(f),e.he=b,$c.forEach(function(a){a()}),Fc());return h}var kd=!1,ld=void 0,md=void 0;
function nd(a,b,c){function d(){Yc=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){},f.exitFullscreen=f.exitFullscreen.bind(document),ld&&f.requestPointerLock(),Yc=!0,md?("undefined"!=typeof SDL&&
(w[SDL.screen>>2]=Ma[SDL.screen>>2]|8388608),od(e.canvas),pd()):od(f)):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),md?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=Ma[SDL.screen>>2]&-8388609),od(e.canvas),pd()):od(f));if(e.onFullScreen)e.onFullScreen(Yc);if(e.onFullscreen)e.onFullscreen(Yc)}ld=a;md=b;qd=c;"undefined"===typeof ld&&(ld=!0);"undefined"===typeof md&&(md=!1);"undefined"===typeof qd&&(qd=null);var f=e.canvas;kd||(kd=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",
d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({ie:c}):
g.requestFullscreen()}function rd(a,b,c){e.printErr("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");rd=function(a,b,c){return nd(a,b,c)};return nd(a,b,c)}var sd=0;function td(a){var b=Date.now();if(0===sd)sd=b+1E3/60;else for(;b+2>=sd;)sd+=1E3/60;setTimeout(a,Math.max(sd-b,0))}
function ud(a){"undefined"===typeof window?td(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||td),window.requestAnimationFrame(a))}function fd(a){e.noExitRuntime=!0;setTimeout(function(){oa||a()},1E4)}
function ed(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var vd=0,wd=0,xd=0,yd=0;
function zd(a){if(Zc)"mousemove"!=a.type&&"mozMovementX"in a?xd=yd=0:(xd=a.movementX||a.mozMovementX||a.webkitMovementX||0,yd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(vd=SDL.ce+xd,wd=SDL.de+yd):(vd+=xd,wd+=yd);else{var b=e.canvas.getBoundingClientRect(),c=e.canvas.width,d=e.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(f=a.pageX-(f+b.left),a=a.pageY-(g+b.top),f*=c/b.width,a*=d/b.height,xd=f-vd,yd=a-wd,vd=f,wd=a)}}function Gc(a,b,c){var d="al "+a;e.readAsync(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));d&&hb()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&gb()}var Ad=[];function pd(){var a=e.canvas;Ad.forEach(function(b){b(a.width,a.height)})}function Bd(a,b,c){od(e.canvas,a,b);c||pd()}
function od(a,b,c){b&&c?(a.Pb=b,a.vb=c):(b=a.Pb,c=a.vb);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}md?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var ad,bd,cd,dd,qd;
function Cd(a,b){Qc=a;Rc=b;if(!Oc)return 1;if(0==a)Lc=function(){var a=Math.max(0,Wc+b-S())|0;setTimeout(Xc,a)},Mc="timeout";else if(1==a)Lc=function(){ud(Xc)},Mc="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);m?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(a),postMessage({target:"setimmediate"})):
postMessage("setimmediate","*")}}Lc=function(){setImmediate(Xc)};Mc="immediate"}return 0}function S(){t()}
function Dd(a,b,c,d,f){e.noExitRuntime=!0;assert(!Oc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Oc=a;Pc=d;var g="undefined"!==typeof d?function(){e.dynCall_vi(a,d)}:function(){e.dynCall_v(a)};var h=Nc;Xc=function(){if(!oa)if(0<Tc.length){var a=Date.now(),b=Tc.shift();b.J(b.X);if(Vc){var c=Vc,d=0==c%1?c-1:Math.floor(c);Vc=b.Sd?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+
b.name+'" took '+(Date.now()-a)+" ms");e.setStatus&&(a=e.statusMessage||"Please wait...",b=Vc,c=Uc.Wd,b?b<c?e.setStatus(a+" ("+(c-b)+"/"+c+")"):e.setStatus(a):e.setStatus(""));h<Nc||setTimeout(Xc,0)}else if(!(h<Nc))if(Sc=Sc+1|0,1==Qc&&1<Rc&&0!=Sc%Rc)Lc();else{0==Qc&&(Wc=S());"timeout"===Mc&&e.L&&(e.printErr("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
Mc="");a:if(!(oa||e.preMainLoop&&!1===e.preMainLoop())){try{g()}catch(z){if(z instanceof fa)break a;z&&"object"===typeof z&&z.stack&&e.printErr("exception thrown: "+[z,z.stack]);throw z;}e.postMainLoop&&e.postMainLoop()}h<Nc||("object"===typeof SDL&&SDL.audio&&SDL.audio.Cb&&SDL.audio.Cb(),Lc())}};f||(b&&0<b?Cd(0,1E3/b):Cd(1,1),Lc());if(c)throw"SimulateInfiniteLoop";}function Ed(a){e.exit(a)}
function Fd(a){if(0===a)return 0;a=D(a);if(!F.hasOwnProperty(a))return 0;Fd.i&&Gd(Fd.i);a=F[a];var b=Ea(a)+1,c=xa(b);c&&Da(a,v,c,b);Fd.i=c;return Fd.i}var Hd=1,Id=0,Jd=[],T=[],Kd=[],U=[],V=[],Ld=[],id=[],Md=null,Nd={},Od={},Pd=[],Qd=4;function W(a){Id||(Id=a)}function Rd(a){for(var b=Hd++,c=a.length;c<b;c++)a[c]=null;return b}var Sd=null,Td=[0];
function hd(a,b){function c(a){d=a.statusMessage||d}"undefined"===typeof b.majorVersion&&"undefined"===typeof b.minorVersion&&(b.majorVersion="undefined"!==typeof WebGL2RenderingContext?2:1,b.minorVersion=0);var d="?";try{a.addEventListener("webglcontextcreationerror",c,!1);try{if(1==b.majorVersion&&0==b.minorVersion)var f=a.getContext("webgl",b)||a.getContext("experimental-webgl",b);else if(2==b.majorVersion&&0==b.minorVersion)f=a.getContext("webgl2",b);else throw"Unsupported WebGL context version "+
majorVersion+"."+minorVersion+"!";}finally{a.removeEventListener("webglcontextcreationerror",c,!1)}if(!f)throw":(";}catch(g){return e.print("Could not create canvas: "+[d,g,JSON.stringify(b)]),0}return f?Ud(f,b):0}
function Ud(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=Rd(id),f={handle:d,attributes:b,version:b.majorVersion,GLctx:a};f.ba=2<=f.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.hb=f);id[d]=f;("undefined"===typeof b.enableExtensionsByDefault||b.enableExtensionsByDefault)&&Vd(f);return d}function jd(a){if(a=id[a])GLctx=e.L=a.GLctx,Md=a}
function Vd(a){a||(a=Md);if(!a.wb){a.wb=!0;var b=a.GLctx;a.be=b.getParameter(b.MAX_VERTEX_ATTRIBS);if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,f){c.drawArraysInstancedANGLE(a,b,d,f)},b.drawElementsInstanced=function(a,b,d,f,g){c.drawElementsInstancedANGLE(a,b,d,f,g)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},
b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.Vd=b.getExtension("EXT_disjoint_timer_query");var g="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear WEBGL_compressed_texture_atc WEBKIT_WEBGL_compressed_texture_pvrtc WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_frag_depth EXT_sRGB WEBGL_draw_buffers WEBGL_shared_resources EXT_shader_texture_lod EXT_color_buffer_float".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=g.indexOf(a)&&b.getExtension(a)})}}var Wd,Xd;function _glDrawArrays(a,b,c){GLctx.drawArrays(a,b,c)}function Yd(a,b,c,d){a*=c;d*=Math.floor((a+d-1)/d);return 0>=b?0:(b-1)*d+a}
function Zd(a,b,c,d,f){switch(b){case 6406:case 6409:case 6402:case 6403:case 36244:b=1;break;case 6410:case 33319:case 33320:b=2;break;case 6407:case 35904:case 36248:b=3;break;case 6408:case 35906:case 36249:b=4;break;default:return W(1280),null}switch(a){case 5121:case 5120:b*=1;break;case 5123:case 36193:case 5131:case 5122:b*=2;break;case 5125:case 5126:case 5124:b*=4;break;case 34042:case 35902:case 33640:case 35899:case 34042:b=4;break;case 33635:case 32819:case 32820:b=2;break;default:return W(1280),
null}c=Yd(c,d,b,Qd);switch(a){case 5120:return v.subarray(f,f+c);case 5121:return A.subarray(f,f+c);case 5122:return qa.subarray(f>>1,f+c>>1);case 5124:return w.subarray(f>>2,f+c>>2);case 5126:return x.subarray(f>>2,f+c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return Ma.subarray(f>>2,f+c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return La.subarray(f>>1,f+c>>1);default:return W(1280),null}}
function $d(a){switch(a){case 5120:return v;case 5121:return A;case 5122:return qa;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return La;case 5124:return w;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return Ma;case 5126:return x;default:return null}}
function ae(a){switch(a){case 5120:case 5121:return 0;case 5122:case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return 1;case 5124:case 5126:case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return 2;default:return 0}}
function be(a,b,c,d){this.id=a;this.y=this.x=0;this.oa=!1;this.ab=this.$a=0;this.width=b;this.height=c;this.Za=b;this.Ya=c;this.title=d;this.attributes=ce;this.buttons=0;this.keys=[];this.ka=[];this.Ga=this.Qa=this.la=this.Xa=this.Z=this.Ia=this.Ua=this.Ma=this.eb=this.title=null}
var X=null,Z=null,de=null,ce=null,ee={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function fe(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function ge(){var a=X,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function he(a){X&&X.Ga&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||e.dynCall_vii(X.Ga,X.id,a))}
function ie(a,b){if(X){var c=fe(a);if(-1!=c){var d=b&&X.keys[c];X.keys[c]=b;X.ka[a]=b;X.Qa&&(d&&(b=2),e.dynCall_viiiii(X.Qa,X.id,c,a,b,ge()))}}}function je(){ke()}function le(){ke()}function me(a){ie(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function ne(a){ie(a.keyCode,0)}function oe(){if(X)for(var a=0;a<X.ka.length;++a)X.ka[a]&&ie(a,0)}function pe(a){X&&(zd(a),a.target==e.canvas&&X.Ia&&e.dynCall_vidd(X.Ia,X.id,vd,wd))}
function qe(a){X&&a.target==e.canvas&&X.Z&&e.dynCall_vii(X.Z,X.id,1)}function re(a){X&&a.target==e.canvas&&X.Z&&e.dynCall_vii(X.Z,X.id,0)}function se(a,b){if(X&&(zd(a),a.target==e.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){X.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else X.buttons&=~(1<<c);X.Ua&&e.dynCall_viiii(X.Ua,X.id,c,b,ge())}}function te(a){X&&se(a,1)}function ue(a){X&&se(a,0)}
function ve(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":break;default:throw"unrecognized mouse wheel event: "+a.type;}if(X&&X.Xa&&a.target==e.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;e.dynCall_vidd(X.Xa,X.id,b,c);a.preventDefault()}}function we(){(e.canvas.requestFullscreen||e.canvas.mozRequestFullScreen||e.canvas.webkitRequestFullScreen||function(){}).apply(e.canvas,[])}var xe={},ye=null,ze=null;
function ke(){if(Sc!==ze||!Sc){ye=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;ze=Sc;for(var a=0;a<ye.length;++a){var b=ye[a];if(b){xe[a]||(console.log("glfw joystick connected:",a),xe[a]={id:y(J(b.id),"i8"),Rd:b.buttons.length,Qd:b.axes.length,buttons:y(Array(b.buttons.length),"i8"),axes:y(Array(4*b.axes.length),"float")});for(var c=xe[a],d=0;d<b.buttons.length;++d)pa(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)pa(c.axes+
4*d,b.axes[d],"float")}else xe[a]&&(console.log("glfw joystick disconnected",a),Gd(xe[a].id),Gd(xe[a].buttons),Gd(xe[a].axes),delete xe[a])}}}
function Ae(a){function b(a){var b="/.glfw_dropped_files/"+a.name.replace(/\//g,"_"),l=new FileReader;l.onloadend=function(h){if(2!=l.readyState)++g,console.log("failed to read dropped file: "+a.name+": "+l.error);else{var q=new Uint8Array(h.target.result);h={};h.flags=h.flags||"w";var E=pc(b,h.flags,h.mode);if("string"===typeof q){var r=new Uint8Array(Ea(q)+1);q=Da(q,r,0,r.length);tc(E,r,0,q,void 0,h.pb)}else if(ArrayBuffer.isView(q))tc(E,q,0,q.byteLength,void 0,h.pb);else throw Error("Unsupported data type");
rc(E);if(++g===f){e.dynCall_viii(X.la,X.id,f,c);for(h=0;h<d.length;++h)Gd(d[h]);Gd(c)}}};l.readAsArrayBuffer(a);var u=y(J(b),"i8");d.push(u);pa(c+4*h,u,"i8*")}if(X&&X.la&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=y(Array(4*a.dataTransfer.files.length),"i8*"),d=[],f=a.dataTransfer.files.length,g=0;yc("/",".glfw_dropped_files");for(var h=0;h<f;++h)b(a.dataTransfer.files[h]);return!1}}function Be(a){if(X&&X.la)return a.preventDefault(),!1}
function Ce(){Ce.i||(Ce.i=[]);Ce.i.push(De());return Ce.i.length-1}var Ee={},Fe=1;function Ge(a,b){Ge.i||(Ge.i={});a in Ge.i||(e.dynCall_v(b),Ge.i[a]=1)}function He(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ie(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Je=[31,29,31,30,31,30,31,31,30,31,30,31],Ke=[31,28,31,30,31,30,31,31,30,31,30,31];
function Le(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(He(a.getFullYear())?Je:Ke)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Me(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function l(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function q(a){a=Le(new Date(a.j+1900,0,1),a.ea);var b=l(new Date(a.getFullYear()+1,0,4));return 0>=h(l(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var r=w[d+40>>2];d={Lb:w[d>>2],Kb:w[d+4>>2],da:w[d+8>>2],K:w[d+12>>2],D:w[d+16>>2],j:w[d+20>>2],bb:w[d+24>>2],ea:w[d+28>>2],ge:w[d+32>>2],Jb:w[d+36>>2],Mb:r?
D(r):""};c=D(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var u in r)c=c.replace(new RegExp(u,"g"),r[u]);var z="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ta="January February March April May June July August September October November December".split(" ");r={"%a":function(a){return z[a.bb].substring(0,3)},"%A":function(a){return z[a.bb]},"%b":function(a){return ta[a.D].substring(0,
3)},"%B":function(a){return ta[a.D]},"%C":function(a){return g((a.j+1900)/100|0,2)},"%d":function(a){return g(a.K,2)},"%e":function(a){return f(a.K,2," ")},"%g":function(a){return q(a).toString().substring(2)},"%G":function(a){return q(a)},"%H":function(a){return g(a.da,2)},"%I":function(a){a=a.da;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.K+Ie(He(a.j+1900)?Je:Ke,a.D-1),3)},"%m":function(a){return g(a.D+1,2)},"%M":function(a){return g(a.Kb,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=
a.da&&12>a.da?"AM":"PM"},"%S":function(a){return g(a.Lb,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.j+1900,a.D+1,a.K,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.j+1900,0,1),c=0===b.getDay()?b:Le(b,7-b.getDay());a=new Date(a.j+1900,a.D,a.K);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Ie(He(a.getFullYear())?Je:Ke,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=l(new Date(a.j+1900,0,4)),c=l(new Date(a.j+1901,0,4)),d=Le(new Date(a.j+
1900,0,1),a.ea);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.j+1900?a.ea+32-b.getDate():a.ea+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.j+1900,a.D+1,a.K,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.j,0,1),c=1===b.getDay()?b:Le(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.j+1900,a.D,a.K);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Ie(He(a.getFullYear())?Je:Ke,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.j+1900).toString().substring(2)},
"%Y":function(a){return a.j+1900},"%z":function(a){a=a.Jb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Mb},"%%":function(){return"%"}};for(u in r)0<=c.indexOf(u)&&(c=c.replace(new RegExp(u,"g"),r[u](d)));u=J(c,!1);if(u.length>b)return 0;v.set(u,a);return u.length-1}uc();Ub=Array(4096);jc(K,"/");O("/tmp");O("/home");O("/home/web_user");
(function(){O("/dev");Gb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});lc("/dev/null",259);Fb(1280,Ib);Fb(1536,Jb);lc("/dev/tty",1280);lc("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else b=n?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};P("/dev","random",b);P("/dev","urandom",b);O("/dev/shm");O("/dev/shm/tmp")})();O("/proc");O("/proc/self");O("/proc/self/fd");
jc({m:function(){var a=Lb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=Sb[+c];if(!b)throw new I(G.A);a={parent:null,m:{Ta:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Ya.unshift(function(){if(!e.noFSInit&&!vc){assert(!vc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");vc=!0;uc();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?P("/dev","stdin",e.stdin):mc("/dev/tty","/dev/stdin");e.stdout?P("/dev","stdout",null,e.stdout):mc("/dev/tty","/dev/stdout");e.stderr?P("/dev","stderr",null,e.stderr):mc("/dev/tty1","/dev/stderr");var a=
pc("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=pc("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=pc("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Za.push(function(){Vb=!1});$a.push(function(){vc=!1;var a=e._fflush;a&&a(0);for(a=0;a<Sb.length;a++){var b=Sb[a];b&&rc(b)}});e.FS_createFolder=xc;e.FS_createPath=yc;e.FS_createDataFile=Ac;e.FS_createPreloadedFile=Ec;e.FS_createLazyFile=Dc;e.FS_createLink=Bc;
e.FS_createDevice=P;e.FS_unlink=nc;Ya.unshift(function(){});$a.push(function(){});if(n){var fs=require("fs"),Pb=require("path");M.Ib()}(function(){if("undefined"!==typeof window){window.addEventListener("gamepadconnected",function(){++Jc});window.addEventListener("gamepaddisconnected",function(){--Jc});var a=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null;a&&(Jc=a.length)}})();
e.requestFullScreen=function(a,b,c){e.printErr("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");e.requestFullScreen=e.requestFullscreen;rd(a,b,c)};e.requestFullscreen=function(a,b,c){nd(a,b,c)};e.requestAnimationFrame=function(a){ud(a)};e.setCanvasSize=function(a,b,c){Bd(a,b,c)};e.pauseMainLoop=function(){Lc=null;Nc++};e.resumeMainLoop=function(){Nc++;var a=Qc,b=Rc,c=Oc;Oc=null;Dd(c,0,!1,Pc,!0);Cd(a,b);Lc()};
e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return gd(a,b,c,d)};
n?S=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?S=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?S=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?S=function(){return performance.now()}:S=Date.now;var GLctx;Sd=new Float32Array(256);for(var Ne=0;256>Ne;Ne++)Td[Ne]=Sd.subarray(0,Ne+1);for(Ne=0;32>Ne;Ne++)Pd.push(Array(Ne));B=ha(4);Pa=Qa=ja(p);Ra=Pa+Va;
Sa=ja(Ra);w[B>>2]=Sa;ia=!0;function J(a,b){var c=Array(Ea(a)+1);a=Da(a,c,0,c.length);b&&(c.length=a);return c}e.wasmTableSize=1232;e.wasmMaxTableSize=1232;e.lb={};
e.mb={abort:t,assert:assert,enlargeMemory:Aa,getTotalMemory:function(){return C},abortOnCannotGrowMemory:function(){t("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+C+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},invoke_ii:function(a,b){try{return e.dynCall_ii(a,b)}catch(c){if("number"!==
typeof c&&"longjmp"!==c)throw c;e.setThrew(1,0)}},invoke_iii:function(a,b,c){try{return e.dynCall_iii(a,b,c)}catch(d){if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},invoke_iiii:function(a,b,c,d){try{return e.dynCall_iiii(a,b,c,d)}catch(f){if("number"!==typeof f&&"longjmp"!==f)throw f;e.setThrew(1,0)}},invoke_iiiii:function(a,b,c,d,f){try{return e.dynCall_iiiii(a,b,c,d,f)}catch(g){if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},invoke_iiiiid:function(a,b,c,d,f,g){try{return e.dynCall_iiiiid(a,
b,c,d,f,g)}catch(h){if("number"!==typeof h&&"longjmp"!==h)throw h;e.setThrew(1,0)}},invoke_iiiiii:function(a,b,c,d,f,g){try{return e.dynCall_iiiiii(a,b,c,d,f,g)}catch(h){if("number"!==typeof h&&"longjmp"!==h)throw h;e.setThrew(1,0)}},invoke_iiiiiid:function(a,b,c,d,f,g,h){try{return e.dynCall_iiiiiid(a,b,c,d,f,g,h)}catch(l){if("number"!==typeof l&&"longjmp"!==l)throw l;e.setThrew(1,0)}},invoke_iiiiiii:function(a,b,c,d,f,g,h){try{return e.dynCall_iiiiiii(a,b,c,d,f,g,h)}catch(l){if("number"!==typeof l&&
"longjmp"!==l)throw l;e.setThrew(1,0)}},invoke_iiiiiiii:function(a,b,c,d,f,g,h,l){try{return e.dynCall_iiiiiiii(a,b,c,d,f,g,h,l)}catch(q){if("number"!==typeof q&&"longjmp"!==q)throw q;e.setThrew(1,0)}},invoke_iiiiiiiii:function(a,b,c,d,f,g,h,l,q){try{return e.dynCall_iiiiiiiii(a,b,c,d,f,g,h,l,q)}catch(r){if("number"!==typeof r&&"longjmp"!==r)throw r;e.setThrew(1,0)}},invoke_iiiiiiiiii:function(a,b,c,d,f,g,h,l,q,r){try{return e.dynCall_iiiiiiiiii(a,b,c,d,f,g,h,l,q,r)}catch(u){if("number"!==typeof u&&
"longjmp"!==u)throw u;e.setThrew(1,0)}},invoke_v:function(a){try{e.dynCall_v(a)}catch(b){if("number"!==typeof b&&"longjmp"!==b)throw b;e.setThrew(1,0)}},invoke_vi:function(a,b){try{e.dynCall_vi(a,b)}catch(c){if("number"!==typeof c&&"longjmp"!==c)throw c;e.setThrew(1,0)}},invoke_vii:function(a,b,c){try{e.dynCall_vii(a,b,c)}catch(d){if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},invoke_viii:function(a,b,c,d){try{e.dynCall_viii(a,b,c,d)}catch(f){if("number"!==typeof f&&"longjmp"!==f)throw f;
e.setThrew(1,0)}},invoke_viiii:function(a,b,c,d,f){try{e.dynCall_viiii(a,b,c,d,f)}catch(g){if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},invoke_viiiii:function(a,b,c,d,f,g){try{e.dynCall_viiiii(a,b,c,d,f,g)}catch(h){if("number"!==typeof h&&"longjmp"!==h)throw h;e.setThrew(1,0)}},invoke_viiiiii:function(a,b,c,d,f,g,h){try{e.dynCall_viiiiii(a,b,c,d,f,g,h)}catch(l){if("number"!==typeof l&&"longjmp"!==l)throw l;e.setThrew(1,0)}},invoke_viiiiiiii:function(a,b,c,d,f,g,h,l,q){try{e.dynCall_viiiiiiii(a,
b,c,d,f,g,h,l,q)}catch(r){if("number"!==typeof r&&"longjmp"!==r)throw r;e.setThrew(1,0)}},___buildEnvironment:qb,___cxa_allocate_exception:function(a){return xa(a)},___cxa_begin_catch:function(a){var b=tb[a];b&&!b.Fa&&(b.Fa=!0,Oe.ja--);b&&(b.Fb=!1);sb.push(a);a:{if(a&&!tb[a])for(c in tb)if(b=+c,tb[b].Ba===a){var c=b;break a}c=a}c&&tb[c].Db++;return a},___cxa_find_matching_catch:ub,___cxa_pure_virtual:function(){oa=!0;throw"Pure virtual function called!";},___cxa_throw:function(a,b,c){tb[a]={Bb:a,
Ba:a,type:b,Ud:c,Db:0,Fa:!1,Fb:!1};rb=a;"uncaught_exception"in Oe?Oe.ja++:Oe.ja=1;throw a;},___cxa_uncaught_exception:function(){return!!Oe.ja},___gxx_personality_v0:function(){},___lock:function(){},___map_file:function(){wb(G.H);return-1},___resumeException:function(a){rb||(rb=a);throw a;},___setErrNo:wb,___syscall140:function(a,b){Q=b;try{var c=Ic();R();var d=R(),f=R(),g=R();sc(c,d,g);w[f>>2]=c.position;c.pa&&0===d&&0===g&&(c.pa=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof
I||t(h),-h.u}},___syscall145:function(a,b){Q=b;try{var c=Ic(),d=R();a:{var f=R();for(b=a=0;b<f;b++){var g=w[d+(8*b+4)>>2],h=c,l=w[d+8*b>>2],q=g,r=void 0,u=v;if(0>q||0>r)throw new I(G.h);if(null===h.fd)throw new I(G.A);if(1===(h.flags&2097155))throw new I(G.A);if(L(h.node.mode))throw new I(G.P);if(!h.f.read)throw new I(G.h);var z="undefined"!==typeof r;if(!z)r=h.position;else if(!h.seekable)throw new I(G.W);var ta=h.f.read(h,u,l,q,r);z||(h.position+=ta);var E=ta;if(0>E){var Y=-1;break a}a+=E;if(E<
g)break}Y=a}return Y}catch(Ob){return"undefined"!==typeof FS&&Ob instanceof I||t(Ob),-Ob.u}},___syscall146:function(a,b){Q=b;try{var c=Ic(),d=R();a:{var f=R();for(b=a=0;b<f;b++){var g=tc(c,v,w[d+8*b>>2],w[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(l){return"undefined"!==typeof FS&&l instanceof I||t(l),-l.u}},___syscall221:function(a,b){Q=b;try{var c=Ic();switch(R()){case 0:var d=R();return 0>d?-G.h:pc(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;
case 4:return d=R(),c.flags|=d,0;case 12:case 12:return d=R(),qa[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-G.h;case 9:return wb(G.h),-1;default:return-G.h}}catch(f){return"undefined"!==typeof FS&&f instanceof I||t(f),-f.u}},___syscall5:function(a,b){Q=b;try{var c=D(R()),d=R(),f=R();return pc(c,d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof I||t(g),-g.u}},___syscall54:function(a,b){Q=b;try{var c=Ic(),d=R();switch(d){case 21509:case 21505:return c.tty?
0:-G.G;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-G.G;case 21519:if(!c.tty)return-G.G;var f=R();return w[f>>2]=0;case 21520:return c.tty?-G.h:-G.G;case 21531:a=f=R();if(!c.f.xb)throw new I(G.G);return c.f.xb(c,d,a);case 21523:return c.tty?0:-G.G;case 21524:return c.tty?0:-G.G;default:t("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof FS&&g instanceof I||t(g),-g.u}},___syscall6:function(a,b){Q=b;try{var c=Ic();rc(c);return 0}catch(d){return"undefined"!==
typeof FS&&d instanceof I||t(d),-d.u}},___syscall91:function(a,b){Q=b;try{var c=R(),d=R(),f=Hc[c];if(!f)return 0;if(d===f.$d){var g=Sb[f.fd],h=f.flags,l=new Uint8Array(A.subarray(c,c+d));g&&g.f.aa&&g.f.aa(g,l,0,d,h);Hc[c]=null;f.kb&&Gd(f.ae)}return 0}catch(q){return"undefined"!==typeof FS&&q instanceof I||t(q),-q.u}},___unlock:function(){},__addDays:Le,__arraySum:Ie,__exit:Ed,__isLeapYear:He,_abort:function(){e.abort()},_emscripten_get_canvas_element_size:function(a,b,c){a?a?("number"==typeof a&&
(a=D(a)),a="#window"==a?window:"#document"==a?document:"#screen"==a?window.screen:"#canvas"==a?e.canvas:"string"==typeof a?document.getElementById(a):a):a=window:a=e.canvas;if(!a)return-4;w[b>>2]=a.width;w[c>>2]=a.height;return 0},_emscripten_get_now:S,_emscripten_longjmp:function(a,b){Kc(a,b)},_emscripten_memcpy_big:function(a,b,c){A.set(A.subarray(b,b+c),a);return a},_emscripten_set_main_loop:Dd,_emscripten_set_main_loop_timing:Cd,_exit:function(a){Ed(a)},_getenv:Fd,_glActiveTexture:function(a){GLctx.activeTexture(a)},
_glAttachShader:function(a,b){GLctx.attachShader(T[a],V[b])},_glBindBuffer:function(a,b){var c=b?Jd[b]:null;35051==a?GLctx.Td=b:35052==a&&(GLctx.rb=b);GLctx.bindBuffer(a,c)},_glBindTexture:function(a,b){GLctx.bindTexture(a,b?Kd[b]:null)},_glBindVertexArray:function(a){GLctx.bindVertexArray(Ld[a])},_glBlendEquationSeparate:function(a,b){GLctx.blendEquationSeparate(a,b)},_glBlendFunc:function(a,b){GLctx.blendFunc(a,b)},_glBlendFuncSeparate:function(a,b,c,d){GLctx.blendFuncSeparate(a,b,c,d)},_glBufferData:function(a,
b,c,d){c?Md.ba?GLctx.bufferData(a,A,d,c,b):GLctx.bufferData(a,A.subarray(c,c+b),d):GLctx.bufferData(a,b,d)},_glClear:function(a){GLctx.clear(a)},_glClearColor:function(a,b,c,d){GLctx.clearColor(a,b,c,d)},_glCompileShader:function(a){GLctx.compileShader(V[a])},_glCreateProgram:function(){var a=Rd(T),b=GLctx.createProgram();b.name=a;T[a]=b;return a},_glCreateShader:function(a){var b=Rd(V);V[b]=GLctx.createShader(a);return b},_glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],f=Jd[d];
f&&(GLctx.deleteBuffer(f),f.name=0,Jd[d]=null,d==Wd&&(Wd=0),d==Xd&&(Xd=0))}},_glDeleteProgram:function(a){if(a){var b=T[a];b?(GLctx.deleteProgram(b),b.name=0,T[a]=null,Nd[a]=null):W(1281)}},_glDeleteShader:function(a){if(a){var b=V[a];b?(GLctx.deleteShader(b),V[a]=null):W(1281)}},_glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],f=Kd[d];f&&(GLctx.deleteTexture(f),f.name=0,Kd[d]=null)}},_glDeleteVertexArrays:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];GLctx.deleteVertexArray(Ld[d]);
Ld[d]=null}},_glDisable:function(a){GLctx.disable(a)},_glDrawArrays:_glDrawArrays,_glEnable:function(a){GLctx.enable(a)},_glEnableVertexAttribArray:function(a){GLctx.enableVertexAttribArray(a)},_glGenBuffers:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createBuffer();if(!d){for(W(1282);c<a;)w[b+4*c++>>2]=0;break}var f=Rd(Jd);d.name=f;Jd[f]=d;w[b+4*c>>2]=f}},_glGenTextures:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createTexture();if(!d){for(W(1282);c<a;)w[b+4*c++>>2]=0;break}var f=Rd(Kd);d.name=
f;Kd[f]=d;w[b+4*c>>2]=f}},_glGenVertexArrays:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createVertexArray();if(!d){for(W(1282);c<a;)w[b+4*c++>>2]=0;break}var f=Rd(Ld);d.name=f;Ld[f]=d;w[b+4*c>>2]=f}},_glGetProgramInfoLog:function(a,b,c,d){a=GLctx.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");0<b&&d?(b=Da(a,A,d,b),c&&(w[c>>2]=b)):c&&(w[c>>2]=0)},_glGetProgramiv:function(a,b,c){if(c)if(a>=Hd)W(1281);else{var d=Nd[a];if(d)if(35716==b)a=GLctx.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),
w[c>>2]=a.length+1;else if(35719==b)w[c>>2]=d.ra;else if(35722==b){if(-1==d.R){a=T[a];var f=GLctx.getProgramParameter(a,GLctx.ACTIVE_ATTRIBUTES);for(b=d.R=0;b<f;++b)d.R=Math.max(d.R,GLctx.getActiveAttrib(a,b).name.length+1)}w[c>>2]=d.R}else if(35381==b){if(-1==d.S)for(a=T[a],f=GLctx.getProgramParameter(a,GLctx.Qb),b=d.S=0;b<f;++b){var g=GLctx.Yd(a,b);d.S=Math.max(d.S,g.length+1)}w[c>>2]=d.S}else w[c>>2]=GLctx.getProgramParameter(T[a],b);else W(1282)}else W(1281)},_glGetShaderInfoLog:function(a,b,
c,d){a=GLctx.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");0<b&&d?(b=Da(a,A,d,b),c&&(w[c>>2]=b)):c&&(w[c>>2]=0)},_glGetShaderiv:function(a,b,c){c?35716==b?(a=GLctx.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1):35720==b?(a=GLctx.getShaderSource(V[a]),w[c>>2]=null===a||0==a.length?0:a.length+1):w[c>>2]=GLctx.getShaderParameter(V[a],b):W(1281)},_glGetString:function(a){if(Od[a])return Od[a];switch(a){case 7936:case 7937:case 37445:case 37446:var b=y(J(GLctx.getParameter(a)),
"i8");break;case 7938:b=GLctx.getParameter(GLctx.VERSION);b=2<=GLctx.canvas.hb.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=y(J(b),"i8");break;case 7939:b=GLctx.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=y(J(c.join(" ")),"i8");break;case 35724:b=GLctx.getParameter(GLctx.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=y(J(b),
"i8");break;default:return W(1280),0}return Od[a]=b},_glGetUniformLocation:function(a,b){b=D(b);var c=0;if(-1!==b.indexOf("]",b.length-1)){var d=b.lastIndexOf("["),f=b.slice(d+1,-1);if(0<f.length&&(c=parseInt(f),0>c))return-1;b=b.slice(0,d)}a=Nd[a];return a?(b=a.cb[b])&&c<b[0]?b[1]+c:-1:-1},_glLinkProgram:function(a){GLctx.linkProgram(T[a]);Nd[a]=null;var b=T[a];Nd[a]={cb:{},ra:0,R:-1,S:-1};a=Nd[a];for(var c=a.cb,d=GLctx.getProgramParameter(b,GLctx.ACTIVE_UNIFORMS),f=0;f<d;++f){var g=GLctx.getActiveUniform(b,
f),h=g.name;a.ra=Math.max(a.ra,h.length+1);-1!==h.indexOf("]",h.length-1)&&(h=h.slice(0,h.lastIndexOf("[")));var l=GLctx.getUniformLocation(b,h);if(null!=l){var q=Rd(U);c[h]=[g.size,q];U[q]=l;for(var r=1;r<g.size;++r)l=GLctx.getUniformLocation(b,h+"["+r+"]"),q=Rd(U),U[q]=l}}},_glPixelStorei:function(a,b){3333==a||3317==a&&(Qd=b);GLctx.pixelStorei(a,b)},_glShaderSource:function(a,b,c,d){for(var f="",g=0;g<b;++g){if(d){var h=w[d+4*g>>2];h=0>h?D(w[c+4*g>>2]):D(w[c+4*g>>2],h)}else h=D(w[c+4*g>>2]);f+=
h}GLctx.shaderSource(V[a],f)},_glTexImage2D:function(a,b,c,d,f,g,h,l,q){if(Md.ba)GLctx.rb?GLctx.texImage2D(a,b,c,d,f,g,h,l,q):0!=q?GLctx.texImage2D(a,b,c,d,f,g,h,l,$d(l),q>>ae(l)):GLctx.texImage2D(a,b,c,d,f,g,h,l,null);else{var r=null;q&&(r=Zd(l,h,d,f,q));GLctx.texImage2D(a,b,c,d,f,g,h,l,r)}},_glTexParameteri:function(a,b,c){GLctx.texParameteri(a,b,c)},_glUniform1f:function(a,b){GLctx.uniform1f(U[a],b)},_glUniform1i:function(a,b){GLctx.uniform1i(U[a],b)},_glUniform4fv:function(a,b,c){if(Md.ba)GLctx.uniform4fv(U[a],
x,c>>2,4*b);else{if(256>=4*b){var d=Td[4*b-1];for(var f=0;f<4*b;f+=4)d[f]=x[c+4*f>>2],d[f+1]=x[c+(4*f+4)>>2],d[f+2]=x[c+(4*f+8)>>2],d[f+3]=x[c+(4*f+12)>>2]}else d=x.subarray(c>>2,c+16*b>>2);GLctx.uniform4fv(U[a],d)}},_glUniformMatrix4fv:function(a,b,c,d){if(Md.ba)GLctx.uniformMatrix4fv(U[a],!!c,x,d>>2,16*b);else{if(256>=16*b){var f=Td[16*b-1];for(var g=0;g<16*b;g+=16)f[g]=x[d+4*g>>2],f[g+1]=x[d+(4*g+4)>>2],f[g+2]=x[d+(4*g+8)>>2],f[g+3]=x[d+(4*g+12)>>2],f[g+4]=x[d+(4*g+16)>>2],f[g+5]=x[d+(4*g+20)>>
2],f[g+6]=x[d+(4*g+24)>>2],f[g+7]=x[d+(4*g+28)>>2],f[g+8]=x[d+(4*g+32)>>2],f[g+9]=x[d+(4*g+36)>>2],f[g+10]=x[d+(4*g+40)>>2],f[g+11]=x[d+(4*g+44)>>2],f[g+12]=x[d+(4*g+48)>>2],f[g+13]=x[d+(4*g+52)>>2],f[g+14]=x[d+(4*g+56)>>2],f[g+15]=x[d+(4*g+60)>>2]}else f=x.subarray(d>>2,d+64*b>>2);GLctx.uniformMatrix4fv(U[a],!!c,f)}},_glUseProgram:function(a){GLctx.useProgram(a?T[a]:null)},_glVertexAttribPointer:function(a,b,c,d,f,g){GLctx.vertexAttribPointer(a,b,c,!!d,f,g)},_glViewport:function(a,b,c,d){GLctx.viewport(a,
b,c,d)},_glfwCreateWindow:function(a,b,c,d){var f;for(f=0;f<Z.length&&null!==Z[f];f++);if(0<f)throw"glfwCreateWindow only supports one window at time currently";var g=f+1;if(0>=a||0>=b)g=0;else{d?we():Bd(a,b);for(f=0;f<Z.length&&null==Z[f];f++);f==Z.length&&(e.L=gd(e.canvas,!0,!0,{antialias:1<ce[135181],depth:0<ce[135173],stencil:0<ce[135174],alpha:0<ce[135172]}));e.L?(a=new be(g,a,b,c),g-1==Z.length?Z.push(a):Z[g-1]=a,X=a,g=a.id):g=0}return g},_glfwGetCursorPos:function(a,b,c){pa(b,vd,"double");
pa(c,wd,"double")},_glfwGetKey:function(a,b){return(a=0>=a||!Z?null:Z[a-1])?a.keys[b]:0},_glfwGetMouseButton:function(a,b){return(a=0>=a||!Z?null:Z[a-1])?0<(a.buttons&1<<b):0},_glfwGetTime:function(){return S()/1E3-de},_glfwGetWindowSize:function(a,b,c){var d=0,f=0;if(a=0>=a||!Z?null:Z[a-1])d=a.width,f=a.height;pa(b,d,"i32");pa(c,f,"i32")},_glfwInit:function(){if(Z)return 1;de=S()/1E3;ce=ee;Z=[];X=null;window.addEventListener("gamepadconnected",je,!0);window.addEventListener("gamepaddisconnected",
le,!0);window.addEventListener("keydown",me,!0);window.addEventListener("keypress",he,!0);window.addEventListener("keyup",ne,!0);window.addEventListener("blur",oe,!0);e.canvas.addEventListener("mousemove",pe,!0);e.canvas.addEventListener("mousedown",te,!0);e.canvas.addEventListener("mouseup",ue,!0);e.canvas.addEventListener("wheel",ve,!0);e.canvas.addEventListener("mousewheel",ve,!0);e.canvas.addEventListener("mouseenter",qe,!0);e.canvas.addEventListener("mouseleave",re,!0);e.canvas.addEventListener("drop",
Ae,!0);e.canvas.addEventListener("dragover",Be,!0);Ad.push(function(a,b){if(X){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(X.$a=X.x,X.ab=X.y,X.Za=X.width,X.Ya=X.height,X.x=X.y=0,X.width=screen.width,X.height=screen.height,X.oa=!0):1==X.oa?(X.x=X.$a,X.y=X.ab,X.width=X.Za,X.height=X.Ya,X.oa=!1):X.width!=a||X.height!=b?(X.width=a,X.height=b):c=!1;c&&(Bd(X.width,X.height,!0),X&&X.eb&&e.dynCall_viii(X.eb,X.id,X.width,X.height),X&&X.Ma&&e.dynCall_viii(X.Ma,
X.id,X.width,X.height))}});return 1},_glfwMakeContextCurrent:function(){},_glfwPollEvents:function(){},_glfwSwapBuffers:function(){},_glfwTerminate:function(){window.removeEventListener("gamepadconnected",je,!0);window.removeEventListener("gamepaddisconnected",le,!0);window.removeEventListener("keydown",me,!0);window.removeEventListener("keypress",he,!0);window.removeEventListener("keyup",ne,!0);window.removeEventListener("blur",oe,!0);e.canvas.removeEventListener("mousemove",pe,!0);e.canvas.removeEventListener("mousedown",
te,!0);e.canvas.removeEventListener("mouseup",ue,!0);e.canvas.removeEventListener("wheel",ve,!0);e.canvas.removeEventListener("mousewheel",ve,!0);e.canvas.removeEventListener("mouseenter",qe,!0);e.canvas.removeEventListener("mouseleave",re,!0);e.canvas.removeEventListener("drop",Ae,!0);e.canvas.removeEventListener("dragover",Be,!0);e.canvas.width=e.canvas.height=1;X=Z=null},_glfwWindowHint:function(a,b){ce[a]=b},_llvm_cttz_i32:function(a){a|=0;return(a?31-(cb(a^a-1)|0)|0:32)|0},_llvm_stackrestore:function(a){var b=
Ce.i[a];Ce.i.splice(a,1);Pe(b)},_llvm_stacksave:Ce,_longjmp:Kc,_pthread_cond_wait:function(){return 0},_pthread_getspecific:function(a){return Ee[a]||0},_pthread_key_create:function(a){if(0==a)return G.h;w[a>>2]=Fe;Ee[Fe]=0;Fe++;return 0},_pthread_once:Ge,_pthread_setspecific:function(a,b){if(!(a in Ee))return G.h;Ee[a]=b;return 0},_strftime:Me,_strftime_l:function(a,b,c,d){return Me(a,b,c,d)},emscriptenWebGLComputeImageSize:Yd,emscriptenWebGLGetHeapForType:$d,emscriptenWebGLGetShiftForType:ae,emscriptenWebGLGetTexPixelData:Zd,
DYNAMICTOP_PTR:B,tempDoublePtr:pb,ABORT:oa,STACKTOP:Qa,STACK_MAX:Ra};var Qe=e.asm(e.lb,e.mb,buffer);e.asm=Qe;
var jb=e.__GLOBAL__I_000101=function(){return e.asm.__GLOBAL__I_000101.apply(null,arguments)},lb=e.__GLOBAL__sub_I_Screen_cpp=function(){return e.asm.__GLOBAL__sub_I_Screen_cpp.apply(null,arguments)},mb=e.__GLOBAL__sub_I_Shader_cpp=function(){return e.asm.__GLOBAL__sub_I_Shader_cpp.apply(null,arguments)},ob=e.__GLOBAL__sub_I_iostream_cpp=function(){return e.asm.__GLOBAL__sub_I_iostream_cpp.apply(null,arguments)},kb=e.__GLOBAL__sub_I_text_cpp=function(){return e.asm.__GLOBAL__sub_I_text_cpp.apply(null,
arguments)},Oe=e.__ZSt18uncaught_exceptionv=function(){return e.asm.__ZSt18uncaught_exceptionv.apply(null,arguments)};e.___cxa_can_catch=function(){return e.asm.___cxa_can_catch.apply(null,arguments)};e.___cxa_demangle=function(){return e.asm.___cxa_demangle.apply(null,arguments)};e.___cxa_is_pointer_type=function(){return e.asm.___cxa_is_pointer_type.apply(null,arguments)};var nb=e.___emscripten_environ_constructor=function(){return e.asm.___emscripten_environ_constructor.apply(null,arguments)};
e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};e.___muldi3=function(){return e.asm.___muldi3.apply(null,arguments)};e.___udivdi3=function(){return e.asm.___udivdi3.apply(null,arguments)};e.__get_environ=function(){return e.asm.__get_environ.apply(null,arguments)};e._bitshift64Lshr=function(){return e.asm._bitshift64Lshr.apply(null,arguments)};e._bitshift64Shl=function(){return e.asm._bitshift64Shl.apply(null,arguments)};
var Ta=e._emscripten_replace_memory=function(){return e.asm._emscripten_replace_memory.apply(null,arguments)},Gd=e._free=function(){return e.asm._free.apply(null,arguments)};e._i64Add=function(){return e.asm._i64Add.apply(null,arguments)};e._i64Subtract=function(){return e.asm._i64Subtract.apply(null,arguments)};e._llvm_bswap_i32=function(){return e.asm._llvm_bswap_i32.apply(null,arguments)};e._main=function(){return e.asm._main.apply(null,arguments)};
var xa=e._malloc=function(){return e.asm._malloc.apply(null,arguments)};e._memcpy=function(){return e.asm._memcpy.apply(null,arguments)};e._memmove=function(){return e.asm._memmove.apply(null,arguments)};e._memset=function(){return e.asm._memset.apply(null,arguments)};e._pthread_cond_broadcast=function(){return e.asm._pthread_cond_broadcast.apply(null,arguments)};e._pthread_mutex_lock=function(){return e.asm._pthread_mutex_lock.apply(null,arguments)};
e._pthread_mutex_unlock=function(){return e.asm._pthread_mutex_unlock.apply(null,arguments)};e._realloc=function(){return e.asm._realloc.apply(null,arguments)};e._saveSetjmp=function(){return e.asm._saveSetjmp.apply(null,arguments)};e._sbrk=function(){return e.asm._sbrk.apply(null,arguments)};e._testSetjmp=function(){return e.asm._testSetjmp.apply(null,arguments)};e.establishStackSpace=function(){return e.asm.establishStackSpace.apply(null,arguments)};
e.getTempRet0=function(){return e.asm.getTempRet0.apply(null,arguments)};e.runPostSets=function(){return e.asm.runPostSets.apply(null,arguments)};var vb=e.setTempRet0=function(){return e.asm.setTempRet0.apply(null,arguments)};e.setThrew=function(){return e.asm.setThrew.apply(null,arguments)};
var Ga=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)},Pe=e.stackRestore=function(){return e.asm.stackRestore.apply(null,arguments)},De=e.stackSave=function(){return e.asm.stackSave.apply(null,arguments)};e.dynCall_ii=function(){return e.asm.dynCall_ii.apply(null,arguments)};e.dynCall_iii=function(){return e.asm.dynCall_iii.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)};
e.dynCall_iiiii=function(){return e.asm.dynCall_iiiii.apply(null,arguments)};e.dynCall_iiiiid=function(){return e.asm.dynCall_iiiiid.apply(null,arguments)};e.dynCall_iiiiii=function(){return e.asm.dynCall_iiiiii.apply(null,arguments)};e.dynCall_iiiiiid=function(){return e.asm.dynCall_iiiiiid.apply(null,arguments)};e.dynCall_iiiiiii=function(){return e.asm.dynCall_iiiiiii.apply(null,arguments)};e.dynCall_iiiiiiii=function(){return e.asm.dynCall_iiiiiiii.apply(null,arguments)};
e.dynCall_iiiiiiiii=function(){return e.asm.dynCall_iiiiiiiii.apply(null,arguments)};e.dynCall_iiiiiiiiii=function(){return e.asm.dynCall_iiiiiiiiii.apply(null,arguments)};e.dynCall_v=function(){return e.asm.dynCall_v.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.dynCall_vii=function(){return e.asm.dynCall_vii.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.dynCall_viii.apply(null,arguments)};
e.dynCall_viiii=function(){return e.asm.dynCall_viiii.apply(null,arguments)};e.dynCall_viiiii=function(){return e.asm.dynCall_viiiii.apply(null,arguments)};e.dynCall_viiiiii=function(){return e.asm.dynCall_viiiiii.apply(null,arguments)};e.dynCall_viiiiiiii=function(){return e.asm.dynCall_viiiiiiii.apply(null,arguments)};e.asm=Qe;e.getMemory=ya;e.addRunDependency=gb;e.removeRunDependency=hb;e.FS_createFolder=xc;e.FS_createPath=yc;e.FS_createDataFile=Ac;e.FS_createPreloadedFile=Ec;
e.FS_createLazyFile=Dc;e.FS_createLink=Bc;e.FS_createDevice=P;e.FS_unlink=nc;e.then=function(a){if(e.calledRun)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}fa.prototype=Error();fa.prototype.constructor=fa;fb=function Re(){e.calledRun||Se();e.calledRun||(fb=Re)};
e.callMain=function(a){a=a||[];za||(za=!0,Wa(Ya));var b=a.length+1,c=Ga(4*(b+1));w[c>>2]=Fa(e.thisProgram);for(var d=1;d<b;d++)w[(c>>2)+d]=Fa(a[d-1]);w[(c>>2)+b]=0;try{var f=e._main(b,c,0);Te(f,!0)}catch(g){g instanceof fa||("SimulateInfiniteLoop"==g?e.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),e.printErr("exception thrown: "+a),e.quit(1,g)))}finally{}};
function Se(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!oa)){za||(za=!0,Wa(Ya));Wa(Za);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&Ue&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();ab.unshift(b)}Wa(ab)}}a=a||e.arguments;if(!(0<db)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)bb();Wa(Xa);0<db||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);b()},1)):b())}}e.run=Se;function Te(a,b){if(!b||!e.noExitRuntime||0!==a){if(!e.noExitRuntime&&(oa=!0,Qa=void 0,Wa($a),e.onExit))e.onExit(a);n&&process.exit(a);e.quit(a,new fa(a))}}e.exit=Te;function t(a){if(e.onAbort)e.onAbort(a);void 0!==a?(e.print(a),e.printErr(a),a=JSON.stringify(a)):a="";oa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=t;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Ue=!0;
e.noInitialRun&&(Ue=!1);e.noExitRuntime=!0;Se();


  return emscripten;
};
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = emscripten;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return emscripten; });
  else if (typeof exports === 'object')
    exports["emscripten"] = emscripten;
  